:features:
  :plan_features:
    :type: string
    :feature_list:
      :split_tickets: 0
      :add_watcher: 1
      :traffic_cop: 2
      :custom_ticket_views: 3
      :supervisor: 4
      :create_observer: 5
      :sla_management: 6
      :email_commands: 7
      :assume_identity: 8
      :rebranding: 9
      :custom_apps: 10
      :custom_ticket_fields: 11
      :custom_company_fields: 12
      :custom_contact_fields: 13
      :occasional_agent: 14
      :allow_auto_suggest_solutions: 15
      :basic_twitter: 16
      :basic_facebook: 17
      :gamification: 18
      :auto_refresh: 19
      :advanced_twitter: 20
      :advanced_facebook: 21
      :surveys: 22
      :scoreboard: 23
      :timesheets: 24
      :custom_domain: 25
      :multiple_emails: 26
      :advanced_reporting: 27
      :default_survey: 28
      :gamification_enable: 29
      :multi_product: 30
      :multiple_business_hours: 31
      :multi_timezone: 32
      :customer_slas: 33
      :layout_customization: 34
      :forums: 35
      :css_customization: 36
      :sitemap: 37
      :multi_language: 38
      :enterprise_reporting: 39
      :dynamic_content: 40
      :requester_widget: 41
      :chat: 42
      :ticket_templates: 43
      :custom_survey: 44
      :collision: 45
      :round_robin: 46
      :custom_ssl: 47
      :custom_roles: 48
      :g10_dummy: 49
      :chat_routing: 50
      :dynamic_sections: 51
      :helpdesk_restriction_toggle: 52
      :round_robin_load_balancing: 53
      :multiple_user_companies: 54
      :multiple_companies_toggle: 55
      :round_robin_on_update: 56
      :mailbox: 57
      :whitelisted_ips: 58
      :branding: 59
      :toggle_branding: 60
      :freshfone_vm_transcription: 61
      :basic_dkim: 62
      :advanced_dkim: 63
      :shared_ownership_toggle: 64
      :link_tickets: 65
      :link_tickets_toggle: 66
      :parent_child_tickets: 67
      :parent_child_tickets_toggle: 68
      :proactive_outreach: 69
      :unique_contact_identifier: 70
      :advanced_search: 71
      :advanced_search_bulk_actions: 72
      :ticket_activity_export: 73
      :system_observer_events: 74
      :private_inline: 75
      :caching: 77
      :collaboration: 78
      :auto_ticket_export: 79
      :skill_based_round_robin: 80
      :user_notifications: 81
      :freshcaller: 82
      :quick_reply: 83
      :falcon: 84
      :denormalized_flexifields: 85
      :support_bot: 86
      :freshcaller_widget: 87
      :image_annotation: 88
      :tam_default_fields: 89
      :todos_reminder_scheduler: 90
      :smart_filter: 91
      :ticket_summary: 92
      :shared_ownership: 93
      :fluffy_forest: 94
      :cascade_dispatcher: 95
      :hipaa: 96
      :custom_encrypted_fields: 97
      :fluffy_higher_plan1: 98
      :google_signin: 99
      :twitter_signin: 100
      :facebook_signin: 101
      :signup_link: 102
      :freshchat: 103
      :session_replay: 104
      :freshconnect: 105
      :captcha: 106
      :moderate_all_posts: 107
      :moderate_posts_with_links: 108
      :hide_portal_forums: 109
      :forum_captcha_disable: 110
      :public_ticket_url: 111
      :redis_display_id: 112
      :chat_enable: 113
      :survey_links: 114
      :unused_115: 115
      :personalized_email_replies: 116
      :anonymous_tickets: 117
      :client_debugging: 118
      :collision_socket: 119
      :single_session_per_user: 120
      :fluffy_higher_plan2: 121
      :suicide_squad_10: 122
      :sandbox: 123
      :call_quality_metrics: 124
      :freshfone_conference: 125
      :unused_126: 126
      :id_less_tickets: 127
      :no_list_view_count_query: 128
      :saml_unspecified_nameid: 129
      :euc_hide_agent_metrics: 130
      :open_solutions: 131
      :auto_suggest_solutions: 132
      :custom_dashboard: 133
      :open_forums: 134
      :reply_to_based_tickets: 135
      :freshfone: 136
      :disable_agent_forward: 137
      :resource_rate_limit: 138
      :domain_restricted_access: 139
      :sort_by_customer_response: 140
      :unresolved_tickets_widget_for_sprout: 141
      :hide_first_response_due: 142
      :field_service_management: 143
      :field_service_management_toggle: 144
      :parent_child_infra: 145
      :enable_multilingual: 146
      :countv2_writes: 147
      :marketplace: 148
      :fa_developer: 149
      :es_multilang_solutions: 150
      :compose_email: 151
      :wild_cards_10: 152
      :contact_company_notes: 153
      :undo_send: 154
      :freshfone_onboarding: 155
      :archive_tickets: 156
      :freshfone_custom_forwarding: 157
      :unused_158: 158
      :report_field_regenerate: 159
      :saml_old_issuer: 160
      :countv2_reads: 161
      :reverse_notes: 162
      :opt_out_analytics: 163
      :disable_old_ui: 164
      :omni_channel_routing: 165
      :segments: 166
      :unused_167: 167
      :ecommerce: 168
      :es_v2_writes: 169
      :fluffy_higher_plan3: 170
      :fluffy_higher_plan4: 171
      :freshfone_call_metrics: 172
      :custom_translations: 173
      :cobrowsing: 174
      :threading_without_user_check: 175
      :freshfone_call_monitoring: 176
      :freshfone_caller_id_masking: 177
      :agent_conference: 178
      :freshfone_warm_transfer: 179
      :canned_forms: 180
      :shadow_fax9: 181
      :shadow_fax10: 182
      :audit_logs_central_publish: 183
      :audit_log_ui: 184
      :restricted_helpdesk: 185
      :freshfone_acw: 186
      :cti: 187
      :all_notify_by_custom_server: 188
      :freshfone_gv_forward: 189
      :advanced_automations: 190
      :freddy_self_service: 191
      :freddy_ultimate: 192
      :agent_scope: 193
      :social_tab: 194
      :untitled_1: 195
      :add_to_response: 196
      :customer_journey: 197
      :customize_table_view: 198
      :custom_password_policy: 199
      :seafarers_8: 200
      :performance_report: 201
      :sla_management_v2: 202
      :scenario_automation: 203
      :ticket_volume_report: 204
      :omni_channel: 205
      :personal_canned_response: 206
      :proactive_spam_detection: 207
      :api_v2: 208
      :bi_reports: 209
      :XX_unused_210: 210
      :unused_211: 211
      :unused_212: 212
      :XX_unused_213: 213
      :updated_twilio_client: 214
      :unused_215: 215
      :unused_216: 216
      :seafarers_1: 217
      :unused_218: 218
      :portal_cc: 219
      :disable_rr_toggle: 220
      :unused_221: 221
      :XX_unused_222: 222
      :analytics_landing_search: 223
      :analytics_landing_data_schedules: 224
      :analytics_landing_new_report: 225
      :analytics_landing_navigation: 226
      :analytics_landing_nlp: 227
      :analytics_report_clone: 228
      :analytics_report_filter: 229
      :analytics_report_schedule: 230
      :analytics_report_export: 231
      :analytics_report_presentation_mode: 232
      :analytics_report_delete: 233
      :analytics_report_save: 234
      :analytics_report_search_widget: 235
      :analytics_report_add_widgets: 236
      :analytics_widget_schedule: 237
      :analytics_widget_export: 238
      :analytics_widget_save: 239
      :analytics_widget_save_as: 240
      :analytics_widget_add_to_reports: 241
      :analytics_widget_change_chart: 242
      :analytics_widget_filter: 243
      :analytics_widget_show_tabular_data: 244
      :analytics_widget_edit_tabular_data: 245
      :analytics_widget_delete: 246
      :analytics_agent_performance: 247
      :analytics_group_performance: 248
      :analytics_helpdesk_in_depth_report: 249
      :analytics_performance_distribution: 250
      :analytics_ticket_volume_trend: 251
      :analytics_customer_analysis: 252
      :analytics_ticket_lifecycle_report: 253
      :analytics_time_sheet_summary_report: 254
      :analytics_satisfaction_survey_report: 255
      :analytics_shared_ownership: 256
      :analytics_linked_tracker_ticket: 257
      :analytics_child_parent_ticket: 258
      :analytics_tags_reports: 259
      :analytics_tickets_resource: 260
      :analytics_timesheet_resource: 261
      :analytics_tags_resource: 262
      :analytics_surveys: 263
      :analytics_survey_results: 264
      :analytics_articles: 265
      :analytics_knowledge_base: 266
      :reports_45: 267
      :reports_46: 268
      :reports_47: 269
      :reports_48: 270
      :reports_49: 271
      :reports_50: 272
      :reports_51: 273
      :reports_52: 274
      :reports_53: 275
      :reports_54: 276
      :reports_55: 277
      :reports_56: 278
      :reports_57: 279
      :reports_58: 280
      :reports_59: 281
      :reports_60: 282
      :reports_61: 283
      :reports_62: 284
      :reports_63: 285
      :reports_64: 286
      :reports_65: 287
      :reports_66: 288
      :reports_67: 289
      :reports_68: 290
      :reports_69: 291
      :reports_70: 292
      :reports_71: 293
      :reports_72: 294
      :reports_73: 295
      :reports_74: 296
      :reports_75: 297
      :reports_76: 298
      :reports_77: 299
      :reports_78: 300
      :reports_79: 301
      :reports_80: 302
      :reports_81: 303
      :reports_82: 304
      :reports_83: 305
      :reports_84: 306
      :reports_85: 307
      :reports_86: 308
      :reports_87: 309
      :reports_88: 310
      :reports_89: 311
      :reports_90: 312
      :reports_91: 313
      :basic_settings_feature: 314
      :untitled_feature_1_dependency_toggle: 315
      :untitled_feature_2_dependency_toggle: 316
      :untitled_setting_1: 317
      :untitled_setting_2: 318
      :untitled_setting_3: 319
      :untitled_setting_4: 320
      :field_service_geolocation: 321
      :reports_99: 322
      :freshreports_analytics: 323
      :disable_old_reports: 324
      :article_filters: 325
      :adv_article_bulk_actions: 326
      :auto_article_order: 327
      :business_hours: 328
      :scenario_automations: 329
      :social_revamp: 330
      :unused_331: 331
      :activity_revamp: 332
      :portal_article_filters: 333
      :article_versioning: 334
      :article_export: 335
      :article_approval_workflow: 336
      :suggested_articles_count: 337
      :article_interlinking: 338
      :kb_increased_file_limit: 339
      :advanced_article_toolbar_options: 340
      :solutions_14: 341
      :solutions_templates: 342
      :solutions_16: 343
      :solutions_17: 344
      :solutions_18: 345
      :solutions_19: 346
      :solutions_20: 347
      :solutions_21: 348
      :solutions_22: 349
      :solutions_23: 350
      :solutions_24: 351
      :solutions_25: 352
      :solutions_26: 353
      :solutions_27: 354
      :solutions_28: 355
      :solutions_29: 356
      :solutions_30: 357
      :detect_thank_you_note_eligible: 358
      :detect_thank_you_note: 359
      :autofaq: 360
      :ticket_properties_suggester_eligible: 361
      :ticket_properties_suggester: 362
      :agent_articles_suggest: 363
      :email_articles_suggest: 364
      :botflow: 365
      :agent_assist_lite: 366
      :robo_assist: 367
      :help_widget: 368
      :help_widget_appearance: 369
      :help_widget_predictive: 370
      :supervisor_custom_status: 371
      :lbrr_by_omniroute: 372
      :secure_attachments: 373
      :next_response_sla: 374
      :fb_ad_posts: 375
      :unlimited_multi_product: 376
      :help_widget_article_customisation: 377
      :sla_reminder_automation: 378
      :pci_compliance_field: 379
      :twitter_field_automation: 380
      :triage: 381
      :advanced_freshcaller: 382
      :email_bot: 383
      :agent_assist_ultimate: 384
      :canned_response_suggest: 385
      :contact_custom_activity_api: 386
      :assets: 387
      :assets_toggle: 388
      :prevent_ticket_creation_for_others: 389
      :custom_source: 390
      :location_tagging: 391
      :robo_assist_ultimate: 392
      :agent_articles_suggest_eligible: 393
      :advanced_ticket_scopes: 394
      :custom_objects: 395
      :quality_management_system: 396
      :kb_allow_base64_images: 397
      :triage_ultimate: 398
      :autofaq_eligible: 399
      :solutions_agent_metrics: 400
      :forums_agent_portal: 401
      :solutions_agent_portal: 402
      :fetch_ticket_from_ref_first: 403
      :skip_ticket_threading: 404
      :helpdesk_tickets_by_product: 405
:selectable_features:
  :redis_display_id: true
  :branding: true
  :es_v2_writes: true
  :gamification_enable: false
  :parent_child_infra: false
  :parent_child_tickets: false
  :link_tickets: false
  :shared_ownership: false
  :advanced_search_bulk_actions: false
  :caching: false
  :private_inline: false
  :freshcaller: false
  :freshcaller_widget: false
  :falcon: false
  :opt_out_analytics: false
  :disable_old_ui: true
  :chat_enable: false
  :survey_links: true
  :personalized_email_replies: false
  :reply_to_based_tickets: true
  :freshfone: false
  :disable_agent_forward: false
  :compose_email: false
  :enable_multilingual: false
  :countv2_writes: false
  :countv2_reads: false
  :freshfone_onboarding: false
  :archive_tickets: false
  :call_quality_metrics: false
  :freshfone_conference: false
  :freshfone_custom_forwarding: false
  :cascade_dispatcher: false
  :custom_encrypted_fields: false
  :undo_send: false
  :google_signin: true
  :twitter_signin: true
  :facebook_signin: true
  :captcha: true
  :hide_portal_forums: false
  :id_less_tickets: false
  :no_list_view_count_query: false
  :client_debugging: false
  :collision_socket: false
  :resource_rate_limit: false
  :domain_restricted_access: false
  :ecommerce: false
  :freshfone_call_metrics: false
  :cobrowsing: false
  :threading_without_user_check: false
  :freshfone_call_monitoring: false
  :freshfone_caller_id_masking: false
  :agent_conference: false
  :freshfone_warm_transfer: false
  :restricted_helpdesk: false
  :freshfone_acw: false
  :cti: false
  :all_notify_by_custom_server: false
  :freshfone_gv_forward: false
  :chat: false
  :freshreports_analytics: false
  :disable_old_reports: false
  :report_field_regenerate: false
  :saml_old_issuer: false
  :es_multilang_solutions: false
  :sort_by_customer_response: false
  :saml_unspecified_nameid: false
  :euc_hide_agent_metrics: false
  :single_session_per_user: false
  :proactive_spam_detection: true
  :bi_reports: false
  :updated_twilio_client: false
  :portal_cc: false
  :disable_rr_toggle: false
  :social_revamp: true
  :activity_revamp: true
  :hide_first_response_due: false
  :fluffy_forest: false
  :fluffy_higher_plan1: false
  :fluffy_higher_plan2: false
  :fluffy_higher_plan3: false
  :fluffy_higher_plan4: false
  :assets: false
  :assets_toggle: false
  :prevent_ticket_creation_for_others: true
  :field_service_geolocation: false
  :location_tagging: false
  :kb_allow_base64_images: false
  :solutions_agent_metrics: false
  :forums_agent_portal: false
  :solutions_agent_portal: false
  :fetch_ticket_from_ref_first: false
  :skip_ticket_threading: false
  :helpdesk_tickets_by_product: false
