# only bitmap features supported here
common: &common
  poduseast: []
  podeucentral: []
  podapsoutheast: []
  podapsouth: []

development:
  <<: *common
staging:
  <<: *common
test:
  <<: *common
production:
  poduseast1: []
  podeucentral1:
    - :session_replay
  podapsoutheast2: []
  podapsouth1: []