--- 
ticket: 
  :index_prefix: tickets_%{index_suffix}
  :alias_prefix: tickets_%{alias_suffix}
note: 
  :index_prefix: tickets_%{index_suffix}
  :alias_prefix: notes_%{alias_suffix}
user: 
  :index_prefix: users_%{index_suffix}
  :alias_prefix: users_%{alias_suffix}
topic: 
  :index_prefix: topics_%{index_suffix}
  :alias_prefix: topics_%{alias_suffix}
post: 
  :index_prefix: topics_%{index_suffix}
  :alias_prefix: posts_%{alias_suffix}
article: 
  :index_prefix: articles_%{index_suffix}
  :alias_prefix: articles_%{alias_suffix}
company: 
  :index_prefix: companies_%{index_suffix}
  :alias_prefix: companies_%{alias_suffix}
tag: 
  :index_prefix: tags_%{index_suffix}
  :alias_prefix: tags_%{alias_suffix}
archiveticket: 
  :index_prefix: archivetickets_%{index_suffix}
  :alias_prefix: archivetickets_%{alias_suffix}
archivenote: 
  :index_prefix: archivetickets_%{index_suffix}
  :alias_prefix: archivenotes_%{alias_suffix}
