---
AU:
  name: Australia
  beta: false
  address_required: true
  local: 3.0
AT:
  name: Austria
  beta: false
  address_required: false
  national: 1.0
  local: 1.0
BE:
  name: Belgium
  beta: false
  address_required: false
  local: 1.0
  national: 1.0
BG:
  name: Bulgaria
  beta: false
  address_required: true
  local: 1.0
BH:
  name: Bahrain
  beta: false
  address_required: false
  local: 8.0
BR:
  name: Brazil
  beta: false
  address_required: false
  local: 3.0
CA:
  name: Canada
  beta: false
  address_required: false
  local: 1.0
  toll_free: 2.0
CH:
  name: Switzerland
  beta: false
  address_required: true
  local: 1.0
CY:
  name: Cyprus
  beta: false
  address_required: false
  national: 4.0
  local: 4.0
CZ:
  name: Czech Republic
  beta: false
  address_required: true
  local: 1.0
DE:
  name: Germany
  beta: false
  address_required: true
  local: 1.0
DK:
  name: Denmark
  beta: false
  address_required: false
  national: 1.0
  local: 1.0
DO:
  name: Dominican Republic
  beta: false
  address_required: false
  local: 7.0
EE:
  name: Estonia
  beta: false
  address_required: false
  national: 1.0
  local: 1.0
ES:
  name: Spain
  beta: false
  address_required: false
  local: 1.0
  national: 1.0
FI:
  name: Finland
  beta: false
  address_required: false
  local: 1.0
  national: 1.0
FR:
  name: France
  beta: false
  address_required: false
  national: 1.0
  local: 1.0
GB:
  name: United Kingdom
  beta: false
  address_required: false
  local: 1.0
  national: 1.0
  toll_free: 2.0
GR:
  name: Greece
  beta: false
  address_required: true
  local: 1.0
HK:
  name: Hong Kong
  beta: false
  address_required: false
  national: 8.0
  local: 8.0
IE:
  name: Ireland
  beta: false
  address_required: false
  national: 1.0
  local: 1.0
IL:
  name: Israel
  beta: false
  address_required: false
  local: 5.0
IT:
  name: Italy
  beta: false
  address_required: false
  local: 1.0
JP:
  name: Japan
  beta: false
  address_required: false
  local: 5.0
LT:
  name: Lithuania
  beta: false
  address_required: false
  local: 1.0
LU:
  name: Luxembourg
  beta: false
  address_required: true
  local: 3.0
LV:
  name: Latvia
  beta: false
  address_required: true
  local: 1.0
MT:
  name: Malta
  beta: false
  address_required: false
  national: 5.0
  local: 5.0
MX:
  name: Mexico
  beta: false
  address_required: true
  local: 3.0
NL:
  name: Netherlands
  beta: false
  address_required: false
  national: 1.0
  local: 1.0
NZ:
  name: New Zealand
  beta: false
  address_required: false
  local: 3.0
PE:
  name: Peru
  beta: false
  address_required: false
  local: 5.0
PL:
  name: Poland
  beta: false
  address_required: false
  local: 1.0
PR:
  name: Puerto Rico
  beta: false
  address_required: false
  national: 8.0
  local: 8.0
PT:
  name: Portugal
  beta: false
  address_required: false
  national: 1.0
  local: 1.0
RO:
  name: Romania
  beta: false
  address_required: true
  local: 5.0
SE:
  name: Sweden
  beta: false
  address_required: false
  local: 1.0
  national: 1.0
SK:
  name: Slovakia
  beta: false
  address_required: true
  local: 1.0
SV:
  name: El Salvador
  beta: false
  address_required: false
  local: 10.0
US:
  name: United States
  beta: false
  address_required: false
  local: 1.0
  toll_free: 2.0
ZA:
  name: South Africa
  beta: false
  address_required: false
  national: 1.0
  local: 1.0
