super_admin:
  - manage_admin 
  - admin_users
  - affiliates 
  - customers 
  - announcements 
  - events 
  - tools 
  - accounts 
  - users 
  - analytics 
  - converstion_metrics 
  - plans 
  - payments 
  - metrics
  - freshfone
  - currency

marketer:
  - affiliates 
  - customers 
  - announcements 
  - events 
  - tools 
  - accounts 
  - users 
  - analytics 
  - converstion_metrics 
  - plans 
  - payments

support:
 - accounts 

freshfone:
 - accounts
 - freshfone


