doc : application/msword
docx: application/vnd.openxmlformats-officedocument.wordprocessingml.document
pdf : application/pdf
txt : text/plain
pps : application/vnd.ms-powerpoint
ppsx: application/vnd.openxmlformats-officedocument.presentationml.slideshow
ppt : application/vnd.ms-powerpoint
pptx: application/vnd.openxmlformats-officedocument.presentationml.presentation
jpeg: image/jpeg
jpg : image/jpeg
png : image/png
tif : image/tiff
tiff: image/tiff
gif : image/gif
xls : application/vnd.ms-excel
xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
mp3 : audio/mpeg
mp4 : video/mp4
wav : audio/wav
ics : text/calendar
eml : message/rfc822
