defaults: &defaults
  poduseast1:
    shard_1: 1
    shard_2: 1000000000
    shard_3: 2000000000
    shard_4: 3000000000
    shard_5: 4000000000
    shard_6: 5000000000
    shard_7: 6000000000
    shard_8: 8000000000
    shard_9: 9000000000
    shard_10: 11000000000
    shard_11: 12000000000
    shard_12: 13000000000
    shard_13: 14000000000
    shard_14: 16000000000
    shard_15: 17000000000
    shard_16: 18000000000
    shard_17: 19000000000
    shard_18: 20000000000
    shard_19: 21000000000
    shard_20: 22000000000
    shard_21: 23000000000
    shard_22: 24000000000
    shard_23_1: 25000000000
    shard_23_2: 26000000000
    shard_23_3: 27000000000
    shard_23_4: 28000000000
    shard_24_1: 29000000000
    shard_24_2: 30000000000
    shard_24_3: 31000000000
    shard_24_4: 32000000000
    shard_24_5: 33000000000
    shard_25_1: 34000000000
    shard_25_2: 35000000000
    shard_25_3: 36000000000
    shard_26_1: 39000000000
    shard_28: 41000000000
    shard_29_1: 42000000000
    shard_29_2: 43000000000
    shard_30: 45000000000
    shard_30_2: 46000000000
    shard_31_1: 44000000000
    shard_32_1: 47000000000
    shard_33_1: 48000000000
    shard_34: 2100000000000
    shard_35: 50000000000
    shard_36_1: 60000000000
    shard_37: 61000000000
    shard_37_2: 62000000000
    shard_38_1: 63000000000
    shard_38_2: 64000000000
    shard_38_3: 65000000000
    shard_39_1: 66000000000
    shard_39_2: 67000000000
    shard_40: 68000000000
    shard_41: 69000000000
    shard_source: 1
    sandbox_shard_us: 11000000000000


  podeucentral1:
    eu_shard_1:   7000000000
    eu_shard_2:  10000000000
    eu_shard_3:  75000000000
    euc_shard_1: 15000000000
    euc_shard_2: 76000000000
    euc_shard_3: 77000000000
    euc_shard_4: 78000000000
    euc_shard_5_1: 79000000000
    euc_shard_5_2: 80000000000
    shard_source: 1
    sandbox_shard_euc: 50000000000000
  podapsoutheast2:
    aus_shard_1: 51000000000
    shard_source: 1
    sandbox_shard_au: 13000000000000
  podapsouth1:
    ind_shard_1: 81000000000
    ind_shard_2: 82000000000
    shard_27_1:  40000000000
    ind_shard_source: 1
    sandbox_shard_ind: 14000000000000

development:
  poduseast:
    shard_1: 1
    shard_2: 1000000000
    shard_3: 2000000000
    shard_4: 3000000000
    shard_5: 4000000000
    shard_6: 5000000000
    shard_7: 6000000000
    sandbox_shard_1: 20000000000

slave:
  <<: *defaults

test:
  poduseast:
    shard_1: 1
    sandbox_shard_1: 2000000000

staging:
  poduseast:
    shard_1: 1
    shard_2: 1000000000
    shard_3: 2000000000
    shard_4: 3000000000
    shard_5: 4000000000
    shard_6: 5000000000
    shard_7: 8000000000
    shard_8: 1400000000
    sandbox_shard_1: 100000000000000
    sandbox_shard_2: 1010000000000
    sandbox_shard_3: 1020000000000
    sandbox_shard_4: 1030000000000
    sandbox_shard_5: 1040000000000
    sandbox_shard_6: 1050000000000

production:
  <<: *defaults
  
