--- 
autopilot:
  common: &common
    contact_url: "https://api2.autopilothq.com/v1/contact"
    trigger_url: "https://api2.autopilothq.com/v1/trigger/%{trigger_code}/contact/%{person_id}"
    contact_with_trigger_url: "https://api2.autopilothq.com/v1/trigger/%{trigger_code}/contact"
  staging: 
    <<: *common
    access_key: "9a0e8aa4369f4103b0bbe9ce8ef19ee5"
    trigger_code: "0002"
    ui_token: "f099ccdcadd749e5abe6202d19d1ddb0656f3506ce2e4c4b8ae063a0ee7f8a10"
  development: 
    <<: *common
    access_key: "9a0e8aa4369f4103b0bbe9ce8ef19ee5"
    trigger_code: "0002"
    ui_token: "f099ccdcadd749e5abe6202d19d1ddb0656f3506ce2e4c4b8ae063a0ee7f8a10"
  test: 
    <<: *common
    access_key: "9a0e8aa4369f4103b0bbe9ce8ef19ee5"
    trigger_code: "0002"
    ui_token: "f099ccdcadd749e5abe6202d19d1ddb0656f3506ce2e4c4b8ae063a0ee7f8a10"
