defaults: &defaults
    communication_url: "localhost"
    secret_key: "3f1fd135e84c2a13c212c11ff2f4b205725faf706345716f4b6996f9f8f2e6472f5784076c4fe102f4c6eae50da0fa59a9cc8cf79fb07ecc1eef62e9d370227f"
    chat_debug: 4
    http_only: 1
    asset_url:
        js: "http://localhost:4000"
        css: "http://localhost:4000"
        cloudfront: "http://localhost:4000"

development:
  <<: *defaults

slave:
  <<: *defaults

test:
  <<: *defaults
