# Used for subscription emails (subscription_notifier.rb)
app_name: Freshdesk
from_email: support@freshdesk.com
cs_email: customersuccess@freshdesk.com
billing_email: billing@freshdesk.com
reports_email: reports@freshdesk.com
integrations_email: integration@freshdesk.com
office365_email: outlook@freshdesk.com
free_plan_agts: 1
app_website: http://www.freshdesk.com
support_url: https://support.freshdesk.com
privacy_policy: https://freshdesk.com/privacy
latest_shard: "shard_7"
feedback_account:
    development: http://localhost.freshdesk-dev.com:3000
    staging: https://feedback1.freshpo.com
    production: https://support.freshdesk.com

attachment:
    attachment_common: &attachment_common
        protocol: http
        port:
    development:
        <<: *attachment_common
        domain:
            poduseast: localhost.freshdesk-dev.com
            podeuwest: localhost.freshdesk-dev.com
            podeucentral: localhost.freshdesk-dev.com
        port: ':3000'
    staging:
        <<: *attachment_common
        domain:
            poduseast: attachment.freshpo.com
            podeuwest: euattachment.freshpo.com
            podeucentral: eucattachment.freshpo.com
        protocol: https
    production:
        <<: *attachment_common
        domain:
            poduseast: attachment.freshdesk.com
            podeuwest: euattachment.freshdesk.com
            podeucentral: eucattachment.freshdesk.com
        protocol: https
    test:
      domain:
          poduseast: localhost.freshdesk-dev.com
          podeuwest: localhost.freshdesk-dev.com
          podeucentral: localhost.freshdesk-dev.com
      port: ':3000'

# Used in account creation (account.rb)
base_domain:
    development: freshdesk-dev.com
    production: freshdesk.com
    staging: freshpo.com
    test: freshpo.com

demo_site:
    development: "localhost:388"
    production:  "demo.freshdesk.com"
    staging:     "demo.freshpo.com"

sub_bcc_email:
    development: "kiran@freshdesk.com"
    production:  "team@freshdesk.com"
    staging:     "support@freshpo.com"

crm:
    development:
       api_key: "08a70b1b65d5775a1138db79ed84313b"
       domain:  "freshdesk-dev"
    production:
       api_key: "7689a7f6686c7ad23037f9ad96e7c4cc"
       domain:  "freshdesk"
    staging:
       api_key: "08a70b1b65d5775a1138db79ed84313b"
       domain:  "freshdesk-dev"

salesforce:
    development:
       consumer_key : "3MVG9Y6d_Btp4xp7._6YSpCqcHkm0UjNo990w4MV9TRff1pc.8Y3.ZHlScJe87hD9Y93UycT6NV3VuWqZwTTq"
       consumer_secret : "8034737126137452216"
       access_token : "5Aep8617VFpoP.M.4tPuMJu8KZ7H4IwcutjcNuNzoB_S7l9x0BM6vIHUXzDWH26X7Kh5XTLcVfdnA=="
       access_secret : "2336849265765064476"
    production:
       consumer_key : "3MVG9Y6d_Btp4xp7._6YSpCqcHkm0UjNo990w4MV9TRff1pc.8Y3.ZHlScJe87hD9Y93UycT6NV3VuWqZwTTq"
       consumer_secret : "8034737126137452216"
       access_token : "5Aep8617VFpoP.M.4tPuMJu8KZ7H4IwcutjcNuNzoB_S7l9x0BM6vIHUXzDWH26X7Kh5XTLcVfdnA=="
       access_secret : "2336849265765064476"
    staging:
       consumer_key : "3MVG9Y6d_Btp4xp7._6YSpCqcHkm0UjNo990w4MV9TRff1pc.8Y3.ZHlScJe87hD9Y93UycT6NV3VuWqZwTTq"
       consumer_secret : "8034737126137452216"
       access_token : "5Aep8617VFpoP.M.4tPuMJu8KZ7H4IwcutjcNuNzoB_S7l9x0BM6vIHUXzDWH26X7Kh5XTLcVfdnA=="
       access_secret : "2336849265765064476"
    test:
       consumer_key : "3MVG9Y6d_Btp4xp7._6YSpCqcHkm0UjNo990w4MV9TRff1pc.8Y3.ZHlScJe87hD9Y93UycT6NV3VuWqZwTTq"
       consumer_secret : "8034737126137452216"
       access_token : "5Aep8617VFpoP.M.4tPuMJu8KZ7H4IwcutjcNuNzoB_S7l9x0BM6vIHUXzDWH26X7Kh5XTLcVfdnA=="
       access_secret : "2336849265765064476"

freshsales:
    development:
      authentication_token: "jxpnk1mNjMvj47mdXBKKVg"
      portal_url: "https://fdadmintest.freshmarketeer.com"
    test:
      authentication_token: "jxpnk1mNjMvj47mdXBKKVg"
      portal_url: "https://fdadmintest.freshmarketeer.com"
    staging:
      authentication_token: "jxpnk1mNjMvj47mdXBKKVg"
      portal_url: "https://fdadmintest.freshmarketeer.com"
    production:
      authentication_token: "1uzGOM_zc-27E1jjJUoTGw"
      portal_url: "https://freshdesk.freshsales.io"

freshchat:
  development:
    token: "b2bd4a97-1290-4dcb-966c-c27547ba9470"
    app_id: "6ba3ce2a-c09a-4247-9b28-83507210bf78"
  test:
    token: "b2bd4a97-1290-4dcb-966c-c27547ba9470"
    app_id: "6ba3ce2a-c09a-4247-9b28-83507210bf78"
  staging:
    token: "b2bd4a97-1290-4dcb-966c-c27547ba9470"
    app_id: "6ba3ce2a-c09a-4247-9b28-83507210bf78"
  production:
    token: "b2bd4a97-1290-4dcb-966c-c27547ba9470"
    app_id: "6ba3ce2a-c09a-4247-9b28-83507210bf78"



marketo:
  development:
    access_key: "freshdesk1_239416885003D634EEFB51"
    secret_key: "987509605187632255000033DD663356EEFF59C93D90"
    api_subdomain: "626-CPN-682"
    api_version: "2_1"
  test:
    access_key: "freshdesk1_239416885003D634EEFB51"
    secret_key: "987509605187632255000033DD663356EEFF59C93D90"
    api_subdomain: "626-CPN-682"
    api_version: "2_1"
  production:
    access_key: "freshdesk1_239416885003D634EEFB51"
    secret_key: "987509605187632255000033DD663356EEFF59C93D90"
    api_subdomain: "626-CPN-682"
    api_version: "2_1"
  staging:
    access_key: "freshdesk1_239416885003D634EEFB51"
    secret_key: "987509605187632255000033DD663356EEFF59C93D90"
    api_subdomain: "626-CPN-682"
    api_version: "2_1"



integrations_url:
    development: "http://localhost:3000"
    test: "https://login.freshpo.com"
    production: "https://login.freshdesk.com"
    # staging: "https://login.freshbugs.com"
    staging: "https://login.freshpo.com"
    # staging: "https://login.freshitil.com"
    #staging: "https://login.freshpo.com"

global_integration_url:
  development: "http://localhost:3000"
  staging: "https://login.freshpo.com"
  production: "https://login.freshdesk.com"
  test: "https://login.freshpo.com"


reseller_portal:
  user_name: "freshdesk"
  password: "FDRP$6M"
  shared_secret: "D7D5892B53FBB8DC4DB53D1DA6156"
  portal_url:
    development: "localhost:3005/freshdesk_webhooks"
    staging: "partners.freshpo.com/freshdesk_webhooks"
    production: "partners.freshdesk.com/freshdesk_webhooks"

natero:
  production:
    url: 'https://api.natero.com/api/v2/accounts'
    api_key: 'icieauqsnc5tdtkz6pbkup5sg8aouptd'

# haproxy common internal domain for redirecting to intended domain
haproxy:
  internal_domain: http://127.0.0.1:8191

# Set this to true if you want to require CC info when creating a trial account for a paid plan
require_payment_info_for_trials: false

# Credit card gateway: One of brain_tree, authorize_net_cim, payment_express, or trust_commerce
gateway: brain_tree

# Used for accessing the site admin controllers, to manage plans,
# discounts, etc.  This is prepended to base_domain, so 'admin'
# here will allow admin.example.com to serve the admin interface.
admin_subdomain: admin

freshops_subdomain:
  poduseast: freshopspoduseast
  podeuwest: freshopspodeuwest
  podeucentral: freshopspodeucentral

partner_subdomain:
  poduseast1: partner
  podeuwest1: partnereu
  podeucentral1: partnereuc  

billing_subdomain: billing

# Show Trial Expiry notifier only if the trail days is less than 100 (dashboard/index.html)
show_trail_notifier_in_days: 30

support_ticket_rate_limit: 20
support_ticket_rate_limit_period: 300

# Frontend Ember config.
falcon_ui:
  index_page: https://s3.amazonaws.com/falconstagingvpc-green/staging/a/index.html

# Internal endpoint to communicate with all Freshdesk microservices under Istio service mesh.
microservices:
  internal_endpoint: http://freshdesk-services.local.internal
