defaults: &defaults
  :aws_hosts:
    - localhost:9200
    - localhost:9200
    - localhost:9200
  :count_host:
    - localhost:9201

development:
  <<: *defaults

slave:
  <<: *defaults

test:
  <<: *defaults
staging:
  <<: *defaults