defaults: &defaults
  imap_application_id: 1
  key: "33E15283B3FE1D1FD22B1619DA9C"
  lang_key: "33E15283B3FE1D1FD22B1619DA9C"
  host: "http://mailservice.freshpo.com"
  dkim_host: "http://mailservice.freshpo.com"
  lang_host: "http://mailservice.freshpo.com"
  timeout: 30
  email_send_urlpath: "api/v1/email/send"
  email_campaign_urlpath: "api/v1/campaign/send"
  account_validate_urlpath: "api/v1/account/validate/"
  sender_config_urlpath: "api/v1/account/senderconfig"
  get_domains: "api/v1/whitelabel/domains/all/"
  configure_domain: "api/v1/whitelabel/configure"
  verify_domain: "api/v1/whitelabel/domains/verify"
  remove_domain: "api/v1/whitelabel/domains"
  fetch_domain: "api/v1/whitelabel/domains"
  ip_pool_category : "35"
  incoming_email_api_key1: "sESov8gFIU03kFEUAZS7ikilAU5Ip2"
  incoming_email_api_key2: "e7d6Gee5HkF6VjD7kIhpu7QmNkDeC6"
  antivirus_urlpath: "/api/v1/antivirus/scan"
  account_destroy_urlpath: "/api/v1/account/delete"
  lang_detect_path: "api/v1/detect/lang"
  ip_pool_names :
    - freshworks_email_high
    - freshworks_email_low

development:
  <<: *defaults

test:
  <<: *defaults
  host: "localhost:3000"
  lang_host: "localhost:3000"
  key: "testkey123"
  lang_key: "testkey123"

staging:
  <<: *defaults

production:
  <<: *defaults