defaults: &defaults
  imap_application_id: 1
  key: "33E15283B3FE1D1FD22B1619DA9C"
  host: "http://mailservice.freshpo.com"
  timeout: 30
  email_send_urlpath: "api/v1/email/send"
  email_campaign_urlpath: "api/v1/campaign/send"
  account_validate_urlpath: "api/v1/account/validate/"
  sender_config_urlpath: "api/v1/account/senderconfig"
  ip_pool_category : "35"
  incoming_email_api_key1: "sESov8gFIU03kFEUAZS7ikilAU5Ip2"
  incoming_email_api_key2: "e7d6Gee5HkF6VjD7kIhpu7QmNkDeC6"
  antivirus_urlpath: "/api/v1/antivirus/scan"
  account_destroy_urlpath: "/api/v1/account/delete"
  ip_pool_names :
    - freshworks_email_high
    - freshworks_email_low

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
  