defaults: &defaults
  detect_thank_you_note:
    url: 'https://thankyou.freddyproject.com/serve/'
    timeout: 1
    confidence_threshold: 80    
    feedback_timeout: 5

  ticket_properties_suggester:
    url: "https://autodispatch-361773157.freshworksapi.com/"
    timeout: 15
    expiry_in_days: 7

  agent_articles_suggest:
    url: "http://system42-serv.staging.freddyproject.com/api/v1/afr/smart_reply"
    secret: '6A25665ECC147A296ECE41EEA68CE'

  system42:
    host: 'https://system42-serv-dev.staging.freddyproject.com'
    onboard_url: 'https://system42-serv-dev.staging.freddyproject.com/api/v1/fd_private/sync_bots'
    secret: 'd320b639-f0f2-465d-bc04-23be99d764cc'
    timeout: 3
    internal: '38e8cbde-83a6-4bba-a5db-12ea4fd3b2f3'

  flowserv:
    host: 'https://api.intfreshbots.com/rest/api/v2/'
    secret: 'FreshDeskDev'
    service: 'bot-admin'
    product_id: '076f18fe945962782e9890b3125bc03e5604c46f'
    timeout: 3

  agent_assist:
    host: 'https://admin.intfreshbots.com/'
    api_host: 'https://api.intfreshbots.com/'
    onboard_url: 'https://api.intfreshbots.com/rest/api/v1/bots'
    client_id: '033cfc72cfeb62f5399237d2554a37d2c98a3c0a'
    product_id: '6d4dbdbdda6e2cbb9905041b56ae7e3f3c77bc15'
    template_hash: '965122f2937e823fbec5cc806e45d5a0c0d5a746'
    jwt_secret: 'RhfEKx8VH8VHu5VswAKxqFT9fRgrBM67KA6fT9tjYV8'
    demo_email: 'rahul.gupta@freshworks.com'
    timeout: 5
    onboard_timeout: 5

  freddy_consumed_session:
    url: 'http://freddyacctusage.stagfreshbots.com/api/v1/accounts'
    app_name: 'freshdesk'
    timeout: 3

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
