development:
  signing_key: "l4nWU7delNXw23nViOFLFGDHkQDKXh_mXv0w9KN_hBY"
  verification_keys: ["iM6YIMpv7N3G4EsCTFTsCgN3GPwshizpsfnYo--4dvw"]
  jwt_default_expiry: 100000
  signup_domain: 'http://d2badcff.ngrok.io:3000'
  region: 'us-east-1'
  domain_prefix: ''
  domain_suffix: ''
  widget_loader_url: '//localhost:8002/fc-widget.js'
  signup_supported: false
test:
  signing_key: "iM6YIMpv7N3G4EsCTFTsCgN3GPwshizpsfnYo--4dvw"
  verification_keys: ["iM6YIMpv7N3G4EsCTFTsCgN3GPwshizpsfnYo--4dvw"]
  jwt_default_expiry: 100
  signup_domain: 'http://localhost:3000'
  domain_prefix: ''
  widget_loader_url: '//localhost:8002/fc-widget.js'