--- 
freshmarketer:
  common: &common
    contact_url: "https://freshworks.freshmarketer.com/mas/api/v1/contacts"
    events_url: "https://freshworks.freshmarketer.com/mas/api/v1/events"
    default_fields_mapping:
      LastName: "last_name"
      FirstName: "first_name"
      Email: "email"
      Phone: "phone"
      MailingCountry: "country"
      MailingCity: "city"
      MailingState State: "state"
      MailingPostalCode: "zipcode"
      Company: "company"
      Twitter: "twitter"
      Linkedin: "linkedin"
      _NewEmail: "new_email"
      GoalName: "goal-name"
      Fdesk Tickets View: 'Fdesk Tickets View'
      Fdesk Sla: 'Fdesk Sla'
      Fdesk Automation: 'Fdesk Automation'
      Fdesk Self Service: 'Fdesk Self Service'
      Fdesk Ticket Assignment: 'Fdesk Ticket Assignment'
      Fdesk Analytics: 'Fdesk Analytics'
      Fdesk Apps: 'Fdesk Apps'
      Fdesk Add Agents: 'Fdesk Add Agents'
      Trial Day: 'Trial Day'
      Fdesk Trial Plan: 'Fdesk Trial Plan'
    custom_fields_mapping:
      Title: "cf_title"
      Industry: "cf_industry"
      NumberOfEmployees: "cf_numberofemployees"
      integer--Account--ID: "cf_fdeskaccountid"
      string--Account--URL: "cf_fdeskaccounturl"
      boolean--Activated: "cf_fdeskactivated"
      string--Other--Referrer: "cf_fdeskotherreferrer"
      string--Signup--Referrer: "cf_fdesksignupreferrer"
      string--Last--Referrer: "cf_fdesklastreferrer"
      string--Plan: "cf_fdeskplan"
      float--Monthly--Revenue: "cf_fdeskmrr"
      integer--Agent--Count: "cf_fdeskagentcount"
      string--Customer--Status: "cf_fdeskcustomerstatus"
      integer--Renewal--Period: "cf_fdeskrenewalperiod"
      boolean--Beacon--Opt--In: "cf_fdeskbeaconoptin"
      string--Upsell--Account--URL: "cf_fdeskupsellurl"
      string--Upsell--Account--ID: "cf_fdeskupsellaccountid"
      boolean--Upsell--Status: "cf_fdeskupsellstatus"
      string--Upsell--Plan: "cf_fdeskupsellplan"
      string--Associated--Accounts: "cf_fdeskassociatedaccounts"
      date--Signup--Date: "cf_fdesksignupdate"
      date--Renewal--Date: "cf_fdeskrenewaldate"
      boolean--Goal--Reports: "cf_fdeskgoalreports"
      boolean--Goal--Ticket: "cf_fdeskgoalticket"
      boolean--Goal--Automation: "cf_fdeskgoalautomation"
      boolean--Goal--Channel: "cf_fdeskgoalchannel"
      boolean--Goal--Self--Service: "cf_fdeskgoalselfservice"
      boolean--Goal--Integration: "cf_fdeskgoalintegration"
  staging: 
    <<: *common
    access_key: "i141ie6mbs865gne8g9h66u0ocr6v5mi0g9o3gla"
    list_id: "1271"
  development: 
    <<: *common
    access_key: "i141ie6mbs865gne8g9h66u0ocr6v5mi0g9o3gla"
    list_id: "1271"
  test: 
    <<: *common
    access_key: "i141ie6mbs865gne8g9h66u0ocr6v5mi0g9o3gla"
    list_id: "1271"
