development:
  node_url: "http://localhost:5000"
  secret_key: "28f7d044ce559caa0b730360c75ddb2dc529fd9a82a91c151ca381a09f01ae5c"
  ops_alert:
    call:
      from: "+12345646409"
      to: ["+918056045905", "+917373157814"]
    mail:
      from: "freshfone@freshworks.com"
      to: "freshfone@freshworks.com"
  freshfone_request:
    to: "support@freshfone.freshdesk.com"
test:
  node_url: "http://localhost:5000"
  secret_key: "28f7d044ce559caa0b730360c75ddb2dc529fd9a82a91c151ca381a09f01ae5c"
  ops_alert:
    call:
      from: "+12345646409"
      to: ["+918056045905", "+917373157814"]
    mail:
      from: "freshfone@freshworks.com"
      to: "freshfone@freshworks.com"
  freshfone_request:
    to: "support@freshfone.freshdesk.com"
