development:
  environment: 'sandbox'
  merchant_id: 'svcr2r64kc272whx'
  public_key: 'tt6ctjn6r6nxcvm6'
  private_key: '3m5tcpr9ht82bvnc'
staging:
  environment: 'sandbox'
  merchant_id: 'svcr2r64kc272whx'
  public_key: 'tt6ctjn6r6nxcvm6'
  private_key: '3m5tcpr9ht82bvnc'
production:
  login: 'demo'
  password: 'password'
test:
  environment: 'test'
  merchant_id: 'svcr2r64kc272whx'
  public_key: 'tt6ctjn6r6nxcvm6'
  private_key: '3m5tcpr9ht82bvnc'
