development: 
  google_oauth2: &id001
    consumer_token: 663183371165-dh9ct05c08k8q00lra341g46asffkaaf.apps.googleusercontent.com
    consumer_secret: 5c7UOsdl0okTN22LcNX0d99i
    options:
      scope: https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
    base_calendar_id: admin@freshpo.com
    access_token: ya29.ngC8UZUDVSg1LD4hRiicPZV68ra3zOeo_ZbcjcEDQDpP_3nc5yv-rIcp
    refresh_token: 1/3VjYf-OcbcbDYiW-lR4XXLqGxg-ZxuTJVat928bCTow
production: 
  google_oauth2:
    consumer_token: 663183371165-dh9ct05c08k8q00lra341g46asffkaaf.apps.googleusercontent.com
    consumer_secret: 5c7UOsdl0okTN22LcNX0d99i
    options:
      scope: https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
    base_calendar_id: admin@freshpo.com
    access_token: ya29.NAAgWqMcjTskQBoAAAAF2754QXBFoiPYmiV4GFoLYlLKxwLyz4CNipj_DqhMmQ
    refresh_token: 1/HdUwbytP5gn1OnX4m-bIzTAmKP3a34D4ktHdm3I7kOM
test: 
  google_oauth2: *id001
slave: 
  google_oauth2: *id001
staging: 
  google_oauth2:
    consumer_token: 663183371165-dh9ct05c08k8q00lra341g46asffkaaf.apps.googleusercontent.com
    consumer_secret: 5c7UOsdl0okTN22LcNX0d99i
    options:
      scope: https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
    base_calendar_id: admin@freshpo.com
    access_token: ya29.ngC8UZUDVSg1LD4hRiicPZV68ra3zOeo_ZbcjcEDQDpP_3nc5yv-rIcp
    refresh_token: 1/3VjYf-OcbcbDYiW-lR4XXLqGxg-ZxuTJVat928bCTow
defaults: 
  google_oauth2: *id001
