helpdesk:
  initializers:
    - githooks
    - mri2.1_patches
    - rails3_patches
    - core_ext/object
    - mail_message_patch
    - authlogic_patch
    - helpdesk
    - api_initializer
    - random_s3_char
    - jbuilder_cache_store
    - action_mailer_callbacks
    - action_mailer_no_tmail
    - activerecord_log
    - admin_roles
    - akismet_config
    - asset_sync
    - aws_s3
    - aws_cloud_front
    - aws/aws_v2
    - aws/dynamo_sdk2
    - aws/lambda
    - aws/sns
    - aws/sqs_sdk2
    - aws/swf
    - aws/cloud_watch
    - belongs_to_account
    - chat_config
    - collab
    - compass
    - concerns
    - count_fix
    - country_list
    - elasticsearch
    - facebook_config
    - gnip_config
    - i18n
    - inflections
    - klout_config
    - liquid
    - load_config
    - tracing
    - memcached
    - mime_types
    - new_rails_defaults
    - pdf_executable_path
    - portal_init
    - query_trace
    - rabbit_mq
    - redis
    - resource_rate_limit
    - redshift
    - resque
    - ruby193_monkey_patches
    - net_http_monkey_patch
    - core_ext/active_record/relation
    - central_publisher/active_record/base
    - secret_token
    - session_store
    - sidekiq
    - marginalia
    - site_cloudfront_asset_host
    - site_keys
    - spam_watcher
    - string_ext
    - archive_datastore
    - time_formats
    - twitter_config
    - social_config
    - virtual_agent
    - white_list_formatted_content
    - will_paginate
    - wrap_parameters
    - big_brother
    - integrations
    - freshmarketer_config
    - iam
    - marketplace_config
    - doorkeeper
    - ebay_config
    - search/v2
    - shoryuken
    - doorkeeper_extension
    - helpdesk_reports/reports_app_config
    - controller_log_subscriber
    - zero_downtime_migration
    - memcache_cleaner
    - action_mailer_log_subscriber
    - email_controller_log_subscriber
    - thrift
    - fd_spam_filter
    - sendgrid_webhook_config
    - message_preview
    - health_check_path
    - api_config_internal_tools
    - sandbox
    - clamav_config
    - inline_manual_config
    - health_check_constants
    - clearbit_config
    - freshpipe
    - zendesk_app_config
    - product_feedback
    - connection_pool_patch
    - imap_patch
    - threaded_init
    - ner_api_config
    - freshid
    - freshquery
    - heap_analytics
    - bot
    - central
    - formserv_config
    - onboarding_config
    - sanitize_monkey_patch
    - paperclip_ssrf_patch
    - app_integration
    - sprockets_monkey_patch
    - facebook_fallback_config
    - hyper_trail
    - default_data_config
    - disposable_email_domains
    - default_data_config
    - emailserv_request
    - saml_config
    - datadog
    - freshvisuals
    - cron_hooks
    - prometheus
    - ruby_thread_config
    - custom_survey_result_key
    - extend_for_shard_mapping
    - coverband
    - silkroad_config
