helpdesk:
  initializers:
    - mri2.1_patches
    - rails3_patches
    - authlogic_patch
    - helpdesk
    - api_initializer
    - jbuilder_cache_store
    - action_mailer_callbacks
    - action_mailer_no_tmail
    - activerecord_log
    - admin_roles
    - akismet_config
    - asset_sync
    - aws_s3
    - aws/aws_v2
    - aws/dynamo_sdk2
    - aws/sqs_sdk2
    - aws/dynamo
    - aws/sns
    - aws/sqs
    - aws/swf
    - aws/cloud_watch
    - aws_forums
    - belongs_to_account
    - chat_config
    - compass
    - concerns
    - count_fix
    - country_list
    - elasticsearch
    - facebook_config
    - global_phone
    - gnip_config
    - i18n
    - inflections
    - klout_config
    - liquid
    - load_config
    - memcached
    - mime_types
    - new_rails_defaults
    - pdf_executable_path
    - portal_init
    - query_trace
    - rabbit_mq
    - redis
    - resource_rate_limit
    - redshift
    - resque
    - riak
    - ruby193_monkey_patches
    - core_ext/active_record/relation
    - secret_token
    - session_store
    - sidekiq
    - site_cloudfront_asset_host
    - site_keys
    - spam_watcher
    - string_ext
    - text_datastore
    - archive_datastore
    - time_formats
    - twitter_config
    - social_config
    - virtual_agent
    - white_list_formatted_content
    - will_paginate
    - wrap_parameters
    - statsd_config
    - big_brother
    - integrations
    - autopilot_config
    - marketplace_config
    - doorkeeper
    - ebay_config
    - search/v2
    - shoryuken
    - doorkeeper_extension
    - helpdesk_reports/reports_app_config
    - controller_log_subscriber
    - zero_downtime_migration
    - action_mailer_log_subscriber
    - email_controller_log_subscriber
    - thrift

