defaults: &defaults
  jwt_secret: "iris&arke"
  service_name: "freshdesk-dev"
  socketioUrl: https://dzvv3qu02a8s8.cloudfront.net/socket.io-1.0.js
  rtsUrl: https://dzvv3qu02a8s8.cloudfront.net/rts-1.0.js
  irisUrl: https://dzvv3qu02a8s8.cloudfront.net/iris-staging-1.0.js
  service_token: ZmlnOmZyZXNoZGVzay1kZXY=
  collector_host: http://iris-staging.freshworksapi.com

  api:
    collector_path: "/collector"

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  service_name: "freshdesk"

production:
  <<: *defaults
  service_name: "freshdesk"
  irisUrl: https://dzvv3qu02a8s8.cloudfront.net/iris-1.0.js
