defaults: &defaults
  agentcollision_host: "agentcollision.freshpo.com/realtime"
  agentcollision_server: "agentcollision.freshpo.com/"
  autorefresh_host: "autorefresh.freshpo.com/realtime"
  autorefresh_server: "autorefresh.freshpo.com/"
  rest_secret_key: "55FB1CB7B69459B798A6A024A9B42410A6A37A6798D0D8D2C677D09DCA8BAFC3"
  auto_refresh_secret: "f2f6ec92b789b2e0a81eea86106e8fc6b789af6c821188a37ae54ea9eeaf8fe9"
  auto_refresh_channel: "refresh"
  agent_collision_channel: "collision"

development:
  <<: *defaults

slave:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  secret_key: "3DBD702F5EF0DC83E51D672DE25D43E3934B536DAD34109E049ADCF0A28F50A6"
