oauth_options:
  salesforce:
    site: https://login.salesforce.com
    authorize_url: /services/oauth2/authorize
    token_url: /services/oauth2/token
  google:
    site: https://www.google.com/

development:
 salesforce:
  consumer_token: 3MVG9Y6d_Btp4xp58zBbA.yojzddB6NCYAJVslYxFc.rabGWq9hI7uRXIKqFvCm4IoVzHOtMEkwrHs7dwcLZa
  consumer_secret: 7977697105566556112
 google:
  consumer_token: 663183371165.apps.googleusercontent.com
  consumer_secret: Td7XaDzfHiNZzZChgmHjJUHy

staging:
 salesforce:
  #freshbugs tokens
  #consumer_token: 3MVG9Y6d_Btp4xp60b6f8yPqWRsZB9nr02K6G7bTQv9dHq8oGEfa3Ys4JNY6sKjyiBktMyYRTUCXelwxQP.Re
  #consumer_secret: 8884773765604569749

  #freshpo
  consumer_token: 3MVG9Y6d_Btp4xp58zBbA.yojzeEqoR3qkUeKQ7WcT5etA69USZCdVPz1gpkLxxdYRYYU3zPsrJd1bzoVRLZf
  consumer_secret: 7527225363657893740
 
 google:
  consumer_token: freshpo.com
  consumer_secret: mZ4Mvav/PzfC5X2lOn2+Qi+o

production:
 salesforce:
  consumer_token: 3MVG9Y6d_Btp4xp58zBbA.yojzd2iOSIknPyJj9LL1Y5IqbQPB9BbzrJRfdkPHFA5QJs9YIQxBJqqX70IXc78
  consumer_secret: 4449493033389148724
 google:
  consumer_token: freshdesk.com
  consumer_secret: f7NgGAv6TKqew3O5Xb85SadF
