oauth_options:
  salesforce:
    site: https://login.salesforce.com
    authorize_url: /services/oauth2/authorize
    token_url: /services/oauth2/token
  google:
    site: https://www.google.com/
  mailchimp:
    authorize_uri: https://login.mailchimp.com/oauth2/authorize
    access_token_uri: https://login.mailchimp.com/oauth2/token
  nimble:
    token_method: :post
    site: "https://api.nimble.com"
  google_oauth2:
    site: https://accounts.google.com
    token_url: /o/oauth2/token
  infusionsoft:
     authorize_url: "https://signin.infusionsoft.com/app/oauth/authorize"
     token_url: "https://api.infusionsoft.com/token"
  box:
    site: https://www.box.com
    token_url: /api/oauth2/token
    authorize_url: /api/oauth2/authorize
  quickbooks:
    site: "https://oauth.intuit.com"
    request_token_path: "/oauth/v1/get_request_token"
    authorize_url: "https://appcenter.intuit.com/Connect/Begin"
    access_token_path: "/oauth/v1/get_access_token" 
  google_contacts:
    site: https://accounts.google.com
    token_url: /o/oauth2/token
  outlook:
    site: https://login.microsoftonline.com
    token_url: /common/oauth2/v2.0/token

development:
 salesforce:
  consumer_token: 3MVG9Y6d_Btp4xp58zBbA.yojzddB6NCYAJVslYxFc.rabGWq9hI7uRXIKqFvCm4IoVzHOtMEkwrHs7dwcLZa
  consumer_secret: 7977697105566556112
 quickbooks:
  consumer_token: qyprdl501v3SKVbWrYDHdAlXxotIh4
  consumer_secret: 2C4hEa7pGCXWwwz1CmJEUU8q7aVsaohZtdqr8V4S
 github:
  consumer_token: 93f887d3b15eee92cd76
  consumer_secret: 542d73b9194cb31ce7e1d49d174cd71bf322a0bd
 mailchimp:
  consumer_token: 437815361144
  consumer_secret: 409c0d6f80c62efcc42e01b6c5569203
 constantcontact:
  consumer_token: f2ff0ffa-5423-4c15-ad80-ac98c2b1191c
  consumer_secret: 0a83bd57fb6946d4aa21faa9515df7e8
 nimble:
  consumer_token: 086decd7b63c4293c766674099b84061
  consumer_secret: 27b2144bd5c63ee7
 surveymonkey:
  consumer_token: kaushiksv
  consumer_secret: AdX7FkGCVV5wYvmD4dhvMnBxmjmS9782
  options:
    api_key: vsg6tg9qsdhmp28q2yugtdng
 google_contacts:
  consumer_token: 872717553632-61vshiv7id01g01ese7sp2vnbj7fccf6.apps.googleusercontent.com
  consumer_secret: UtAAhjbukdfktyIuxWQovVxE
 google_oauth2: # Used by Google portal sso login, google calendar, google marketplace sso app.
  consumer_token: 364422961642-4fr54sficbm151u7f5is9722er6vcjsu.apps.googleusercontent.com
  client_id_ios: 663183371165-qov5cti179dlnlcv85rkcgce2g2s59fb.apps.googleusercontent.com
  client_id_iosv4_classic: 663183371165-lv3s96hi2hch71mda41luq5b9b5v5h5f.apps.googleusercontent.com
  consumer_secret: cBiFYwJm90bqfmBt7gg3Rxqe 
 google_gadget_oauth2:
  consumer_token: 593295161831-52fdiqmli0c9613kld5ilj0nueb87htn.apps.googleusercontent.com
  consumer_secret: cK1hUwD5fyjV5tgS3mn_Ad2M
 shopify:
  consumer_token: b78ef7808d2dba974b17fd21dc94201f
  consumer_secret: 5c1ec02d8e143e1f14505f008eeafdaf
  options:
    scope: 'read_all_orders'
 box:
  consumer_token: vyexjzanqd64g8bj1w2cjy1drmv0gfgn
  consumer_secret: pvRFRQ0vMacLUqRmavgdzGCObBPNbEux
 slack:
   consumer_token: "3575209657.3577497590"
   consumer_secret: 7193779dab625ec3e6764dd5df21309e
   slash_command_token: v38nfGRW4zN7Oe5DgeKdUCL7
 infusionsoft:
   consumer_token:  pymmum7erkmq5vm4vsbqamut
   consumer_secret: DzWRNku2hu
 outlook_contacts:
   consumer_token: fc02555f-2d3b-47c4-a66f-7a45d15c2a1a
   consumer_secret: vcx3eeApBi82xmpXE2CDjzt
 salesforce_v2:
   consumer_token:  3MVG9y6x0357HledW5ceTn9ZT16SJfkv9A5rd60nQVZoY4em5Pnpfx5ghPc.Y8KfMefmzdKWgYNXc9jLYBnlz
   consumer_secret: 6487752873062448676
 microsoft_teams:
   consumer_token: f4db5703-88f5-4db1-ad18-ce960d35a7ef
   consumer_secret: DdUBGab3Jqf38keGDKShsVU
 google_hangout_chat:
   consumer_token: 339129576090-t5laj8ambvi4266e0h3u5rfjc65hr67t.apps.googleusercontent.com
   consumer_secret: Cmc8UF5d4uZO5a3bX1-uwC-9
 outlook:
   consumer_token: 297394a7-fbe3-43fd-8b54-8c8ba7eb00b2
   consumer_secret: QWo9SZb9ng~Mpc64.8M2B.Pd11kD~wyg4A

defaults: &defaults
 salesforce:
  consumer_token: 3MVG9Y6d_Btp4xp58zBbA.yojzddB6NCYAJVslYxFc.rabGWq9hI7uRXIKqFvCm4IoVzHOtMEkwrHs7dwcLZa
  consumer_secret: 7977697105566556112
 quickbooks:
  consumer_token: qyprdl501v3SKVbWrYDHdAlXxotIh4
  consumer_secret: 2C4hEa7pGCXWwwz1CmJEUU8q7aVsaohZtdqr8V4S
 google_contacts:
  consumer_token: 872717553632-61vshiv7id01g01ese7sp2vnbj7fccf6.apps.googleusercontent.com
  consumer_secret: UtAAhjbukdfktyIuxWQovVxE
 google_oauth2:
  consumer_token: 663183371165-dh9ct05c08k8q00lra341g46asffkaaf.apps.googleusercontent.com
  client_id_ios: 663183371165-qov5cti179dlnlcv85rkcgce2g2s59fb.apps.googleusercontent.com
  client_id_iosv4_classic: 663183371165-lv3s96hi2hch71mda41luq5b9b5v5h5f.apps.googleusercontent.com
  consumer_secret: 5c7UOsdl0okTN22LcNX0d99i
 google_gadget_oauth2:
  consumer_token: 593295161831-52fdiqmli0c9613kld5ilj0nueb87htn.apps.googleusercontent.com
  consumer_secret: cK1hUwD5fyjV5tgS3mn_Ad2M
 shopify:
  consumer_token: b78ef7808d2dba974b17fd21dc94201f
  consumer_secret: 5c1ec02d8e143e1f14505f008eeafdaf
  options:
    scope: 'read_all_orders'
 slack:
   consumer_token: "3575209657.3577497590"
   consumer_secret: 7193779dab625ec3e6764dd5df21309e
   slash_command_token: v38nfGRW4zN7Oe5DgeKdUCL7
 outlook_contacts:
   consumer_token: fc02555f-2d3b-47c4-a66f-7a45d15c2a1a
   consumer_secret: vcx3eeApBi82xmpXE2CDjzt
 salesforce_v2:
   consumer_token:  3MVG9y6x0357HledW5ceTn9ZT16SJfkv9A5rd60nQVZoY4em5Pnpfx5ghPc.Y8KfMefmzdKWgYNXc9jLYBnlz
   consumer_secret: 6487752873062448676
 microsoft_teams:
   consumer_token: f4db5703-88f5-4db1-ad18-ce960d35a7ef
   consumer_secret: DdUBGab3Jqf38keGDKShsVU
 google_hangout_chat:
   consumer_token: 339129576090-t5laj8ambvi4266e0h3u5rfjc65hr67t.apps.googleusercontent.com
   consumer_secret: Cmc8UF5d4uZO5a3bX1-uwC-9
 outlook:
   consumer_token: 297394a7-fbe3-43fd-8b54-8c8ba7eb00b2
   consumer_secret: QWo9SZb9ng~Mpc64.8M2B.Pd11kD~wyg4A

test:
 <<: *defaults

slave:
 <<: *defaults


test:
 <<: *defaults

slave:
 <<: *defaults


staging:
 salesforce:
  consumer_token: 3MVG9Y6d_Btp4xp58zBbA.yojzeEqoR3qkUeKQ7WcT5etA69USZCdVPz1gpkLxxdYRYYU3zPsrJd1bzoVRLZf
  consumer_secret: 7527225363657893740
 quickbooks:
  consumer_token: qyprdl501v3SKVbWrYDHdAlXxotIh4
  consumer_secret: 2C4hEa7pGCXWwwz1CmJEUU8q7aVsaohZtdqr8V4S
 github:
  consumer_token: 93f887d3b15eee92cd76
  consumer_secret: 542d73b9194cb31ce7e1d49d174cd71bf322a0bd
 google_oauth2:
  consumer_token: 663183371165-dh9ct05c08k8q00lra341g46asffkaaf.apps.googleusercontent.com
  client_id_ios: 663183371165-0s9usgo31k637fe78gt4nq813tkb4t4g.apps.googleusercontent.com
  client_id_iosv4_classic: 663183371165-lv3s96hi2hch71mda41luq5b9b5v5h5f.apps.googleusercontent.com
  consumer_secret: 5c7UOsdl0okTN22LcNX0d99i
 google_contacts:
  consumer_token: 872717553632-61vshiv7id01g01ese7sp2vnbj7fccf6.apps.googleusercontent.com
  consumer_secret: UtAAhjbukdfktyIuxWQovVxE
 google_gadget_oauth2:
  consumer_token: 593295161831-52fdiqmli0c9613kld5ilj0nueb87htn.apps.googleusercontent.com
  consumer_secret: cK1hUwD5fyjV5tgS3mn_Ad2M
 mailchimp:
  consumer_token: 187267923355
  consumer_secret: 0c8b6473fe421fa60dbd0f3befc4f219
 constantcontact:
  consumer_token: 918a740e-9f25-4471-a625-067f730b7c6e
  consumer_secret: 14f777db3c414452a51925363001eda5
 nimble:
  consumer_token: 1gl1qsgovonhnztkte7wxdv93xms7zz0f82oxx
  consumer_secret: 3mtvtpzzl9bqus9iq07
 surveymonkey:
  consumer_token: kaushiksv
  consumer_secret: kttMNYcFuwHjKchhrDCYkdVNpQn4VXFb
  options:
    api_key: cjw2pjzf2s9fbvkz8863wwmt
 shopify:
  consumer_token: b78ef7808d2dba974b17fd21dc94201f
  consumer_secret: 5c1ec02d8e143e1f14505f008eeafdaf
  options:
    scope: 'read_all_orders'   
 box:
  consumer_token: zkc8ikgqnaxxp8d8hmof0de1777zmcou
  consumer_secret: ygt0d5OC2EjOjBzTmnB3QUaVD0vZ9pem
 slack:
   consumer_token: "3575209657.3577656254"
   consumer_secret: 40e3176389a2255436efedfdd5f9d76a
   slash_command_token: ORUuUjH7ru6vOEfZ0eezHVA2
 infusionsoft:
   consumer_token:  pymmum7erkmq5vm4vsbqamut
   consumer_secret: DzWRNku2hu
 outlook_contacts:
   consumer_token: 83ffd1da-0e5a-427f-9986-a8879b7a4aca
   consumer_secret: bRhQjg9xynB92EEnmjEWxMX
 salesforce_v2:
   consumer_token:  3MVG9y6x0357HledW5ceTn9ZT1.KSsISjCgRJHBn4GG_r_Meq9Zzoc7Xvo_j3UfYqWRenDdf9Tg==
   consumer_secret: 5689067073667055939
 outlook:
   consumer_token: 297394a7-fbe3-43fd-8b54-8c8ba7eb00b2
   consumer_secret: QWo9SZb9ng~Mpc64.8M2B.Pd11kD~wyg4A

production:
 salesforce:
  consumer_token: 3MVG9Y6d_Btp4xp58zBbA.yojzd2iOSIknPyJj9LL1Y5IqbQPB9BbzrJRfdkPHFA5QJs9YIQxBJqqX70IXc78
  consumer_secret: 4449493033389148724
 quickbooks:
  consumer_token: qyprdspxhaEDF9y8hixSOacRuh4lYt
  consumer_secret: ifISBYQG8peHZZUbeUaVgjOpl0VN9UYTe4KoxEXw
 github:
  consumer_token: 9b721c6fe3d0437a8135
  consumer_secret: 897f8d8d2198b1aacd77dc67112332fe0af48a5c
 google_contacts:
  consumer_token: 354224567032-abbutsrfm490t6i3h6ulf41go7sh216e.apps.googleusercontent.com
  consumer_secret: X2HZKWNsAlVssUgWRaimPMS4
 google_oauth2:
  consumer_token: 367378856688.apps.googleusercontent.com
  client_id_ios: 663183371165-0s9usgo31k637fe78gt4nq813tkb4t4g.apps.googleusercontent.com
  client_id_iosv4_classic: 663183371165-lv3s96hi2hch71mda41luq5b9b5v5h5f.apps.googleusercontent.com
  consumer_secret: M0tVzcR4cSL-pRxDUqSV2FH1
 google_gadget_oauth2:
  consumer_token: 287551691553-uticbd9oktcqodm81m9hcb2oeolinkev.apps.googleusercontent.com
  consumer_secret: QWzwA3yw6tmfN6-J5apF7etN
 mailchimp:
  consumer_token: 560756408749
  consumer_secret: d30b60816fe878cf6ea67489b7c47dad
 constantcontact:
  consumer_token: 915f92ab-c49e-4fbc-9322-4606ceede9cd
  consumer_secret: 5f2b1af85f5d40de97b66af3994361b5
 nimble:
  consumer_token: 086decd7b63c4293c766674099b84061
  consumer_secret: 27b2144bd5c63ee7
 surveymonkey:
  consumer_token: freshdesk
  consumer_secret: AgxG9yrJY9rS2mWW9M2tJaQEATXjvBCm
  options:
    api_key: d499g57y8synva8crhycgmfx
 shopify:
  consumer_token: b78ef7808d2dba974b17fd21dc94201f
  consumer_secret: 5c1ec02d8e143e1f14505f008eeafdaf
  options:
    scope: 'read_all_orders'
 box:
  consumer_token: itfsn1ixctz4uwru9d03bozxo92bwnh8
  consumer_secret: 8BcKLFpMi26RxvQhQxTslPlkS1A0rJXV
 slack:
   consumer_token: "3575209657.3866308321"
   consumer_secret: 19210e220ec23853881fdbbaa9aa0a5b
   slash_command_token: v38nfGRW4zN7Oe5DgeKdUCL7
 infusionsoft:
   consumer_token:  pymmum7erkmq5vm4vsbqamut
   consumer_secret: DzWRNku2hu
 outlook_contacts:
   consumer_token: 83ffd1da-0e5a-427f-9986-a8879b7a4aca
   consumer_secret: bRhQjg9xynB92EEnmjEWxMX
 salesforce_v2:
   consumer_token:  3MVG9y6x0357HledW5ceTn9ZT13z3OsaOTdri1OzXuBmoGIB8Bh8G52UfZAWSuUIKX4PuaiRtQMOOpvzRUDYH
   consumer_secret: 5910100902142393254
 outlook:
   consumer_token: f28187ae-6f21-4f42-a4ef-4fbf9b6548bf
   consumer_secret: J6YYDia18Vq2m7h_EORDLl_M2c3X-svw-K
