--- 
:privileges: 
  :manage_canned_responses: 25
  :view_admin: 23
  :manage_tickets: 0
  :publish_solution: 11
  :edit_topic: 17
  :edit_conversation: 5
  :manage_supervisor_rules: 27
  :manage_account: 31
  :forward_ticket: 2
  :view_contacts: 19
  :edit_time_entries: 8
  :client_manager: 32
  :edit_ticket_properties: 4
  :manage_solutions: 13
  :edit_note: 6
  :reply_ticket: 1
  :manage_users: 24
  :view_forums: 14
  :manage_contacts: 20
  :manage_scenario_automation_rules: 28
  :delete_contact: 21
  :manage_dispatch_rules: 26
  :delete_ticket: 9
  :manage_forums: 15
  :view_time_entries: 7
  :merge_or_split_ticket: 3
  :view_reports: 22
  :admin_tasks: 30
  :create_topic: 16
  :manage_email_settings: 29
  :view_solutions: 10
  :delete_solution: 12
  :delete_topic: 18
  :export_tickets: 35
  :edit_private_note: 36
  :assign_agent: 37
  :assign_group: 38
  :import_customers: 39
  :export_customers: 40
  :export_reports: 41
  :create_solution_draft: 42
  :view_social: 43
  :social_convert_to_ticket: 44
  :social_reply_and_compose_post: 45
  :manage_social_response: 46
  :phone_attend_call: 47
  :phone_make_call: 48
  :phone_export_call_history: 49
  :manage_dashboard: 50
  :untitled_core_supervisor_6: 51
  :compose_email: 52
  :manage_customer_list: 53
  :livechat_admin_tasks: 54
  :livechat_manage_visitor: 55
  :livechat_view_transcripts: 56
  :livechat_edit_transcripts: 57
  :livechat_delete_transcripts: 58
  :livechat_accept_chat: 59
  :livechat_initiat_agent_chat: 60
  :livechat_view_visitors: 61
  :livechat_intiate_visitor_chat: 62
  :livechat_shadow_chat: 63
  :livechat_export_transcripts: 64
  :livechat_manage_shortcodes: 65
  :livechat_view_reports: 66
  :untitled_core_acc_admin_1: 67
  :untitled_core_acc_admin_2: 68
  :untitled_core_acc_admin_3: 69
  :untitled_core_acc_admin_4: 70
  :untitled_core_acc_admin_5: 71
  :untitled_core_admin_1: 72
  :untitled_core_admin_2: 73
  :untitled_core_admin_3: 74
  :untitled_core_admin_4: 75
  :untitled_core_admin_5: 76
  :untitled_core_supervisor_1: 77
  :untitled_core_supervisor_2: 78
  :untitled_core_supervisor_3: 79
  :untitled_core_supervisor_4: 80
  :untitled_core_supervisor_5: 81
  :untitled_core_agent_1: 82
  :untitled_core_agent_2: 83
  :untitled_core_agent_3: 84
  :untitled_core_agent_4: 85
  :untitled_core_agent_5: 86
  :solution_view_reports: 87
  :solution_exports: 88
  :forums_view_reports: 89
  :forums_exports: 90
  :forums_admin_moderator: 91
  :solution_delete_versions: 92
  :solution_restore_versions: 93
  :solution_view_versions: 94
  :forum_advanced_moderator: 95
  :forum_basic_moderator: 96
  :untitled_solution_admin_1: 97
  :untitled_forums_admin_1: 98
  :untitled_solution_supervisor_1: 99
  :untitled_solution_supervisor_2: 100
  :untitled_forums_supervisor_1: 101
  :untitled_forums_supervisor_2: 102
  :untitled_solution_agent_1: 103
  :untitled_solution_agent_2: 104
  :untitled_solution_agent_3: 105
  :untitled_forum_agent_1: 106
  :untitled_forum_agent_2: 107
  :untitled_forum_agent_3: 108
  :manage_ticket_templates: 109
  :spam_ticket: 110
:max_value: 110
