--- 
:privileges: 
  :manage_canned_responses: 25
  :view_admin: 23
  :manage_tickets: 0
  :publish_solution: 11
  :edit_topic: 17
  :edit_conversation: 5
  :manage_supervisor_rules: 27
  :manage_account: 31
  :forward_ticket: 2
  :view_contacts: 19
  :edit_time_entries: 8
  :client_manager: 32
  :edit_ticket_properties: 4
  :manage_solutions: 13
  :edit_note: 6
  :reply_ticket: 1
  :manage_users: 24
  :view_forums: 14
  :manage_contacts: 20
  :manage_scenario_automation_rules: 28
  :delete_contact: 21
  :manage_dispatch_rules: 26
  :delete_ticket: 9
  :manage_forums: 15
  :view_time_entries: 7
  :merge_or_split_ticket: 3
  :view_reports: 22
  :admin_tasks: 30
  :create_topic: 16
  :manage_email_settings: 29
  :view_solutions: 10
  :delete_solution: 12
  :delete_topic: 18
  :export_tickets: 35
  :edit_private_note: 36
  :assign_agent: 37
  :assign_group: 38
  :import_customers: 39
  :export_customers: 40
  :export_reports: 41
  :create_solution_draft: 42
  :view_social: 43
  :social_convert_to_ticket: 44
  :social_reply_and_compose_post: 45
  :manage_social_response: 46
  :phone_attend_call: 47
  :phone_make_call: 48
  :phone_export_call_history: 49
  :manage_ticket_list_views: 50
  :untitled_core_supervisor_6: 51
  :compose_email: 52
  :manage_customer_list: 53
  :livechat_admin_tasks: 54
  :livechat_manage_visitor: 55
  :livechat_view_transcripts: 56
  :livechat_edit_transcripts: 57
  :livechat_delete_transcripts: 58
  :livechat_accept_chat: 59
  :livechat_initiat_agent_chat: 60
  :livechat_view_visitors: 61
  :livechat_intiate_visitor_chat: 62
  :livechat_shadow_chat: 63
  :livechat_export_transcripts: 64
  :livechat_manage_shortcodes: 65
  :livechat_view_reports: 66
  :untitled_core_acc_admin_1: 67
  :untitled_core_acc_admin_2: 68
  :untitled_core_acc_admin_3: 69
  :untitled_core_acc_admin_4: 70
  :untitled_core_acc_admin_5: 71
  :manage_tags: 72
  :manage_skills: 73
  :manage_bots: 74
  :manage_segments: 75
  :manage_proactive_outreaches: 76
  :edit_ticket_skill: 77
  :manage_dashboard: 78
  :view_analytics: 79
  :untitled_core_supervisor_4: 80
  :untitled_core_supervisor_5: 81
  :create_tags: 82
  :view_bots: 83
  :view_field_tech_location: 84
  :untitled_core_agent_4: 85
  :untitled_core_agent_5: 86
  :solution_view_reports: 87
  :solution_exports: 88
  :forums_view_reports: 89
  :forums_exports: 90
  :forums_admin_moderator: 91
  :solution_delete_versions: 92
  :solution_restore_versions: 93
  :solution_view_versions: 94
  :forum_advanced_moderator: 95
  :forum_basic_moderator: 96
  :manage_solution_templates: 97
  :untitled_forums_admin_1: 98
  :export_articles: 99
  :untitled_solution_supervisor_2: 100
  :untitled_forums_supervisor_1: 101
  :untitled_forums_supervisor_2: 102
  :create_and_edit_article: 103
  :approve_article: 104
  :untitled_solution_agent_3: 105
  :untitled_forum_agent_1: 106
  :untitled_forum_agent_2: 107
  :untitled_forum_agent_3: 108
  :manage_ticket_templates: 109
  :spam_ticket: 110
  :manage_availability: 111
  :contractor: 112
  :manage_calls: 113
  :manage_companies: 114
  :delete_company: 115
  :manage_requester_notifications: 116
  :untitled_core_agent_2019_6: 117
  :untitled_core_agent_2019_7: 118
  :untitled_core_agent_2019_8: 119
  :schedule_fsm_dashboard: 120
  :access_to_map_view: 121
  :manage_service_task_automation_rules: 122
  :untitled_core_admin_2019_4: 123
  :untitled_core_admin_2019_5: 124
  :untitled_core_supervisor_2019_1: 125
  :untitled_core_supervisor_2019_2: 126
  :untitled_core_supervisor_2019_3: 127
  :untitled_core_supervisor_2019_4: 128
  :untitled_core_supervisor_2019_5: 129
  :publish_approved_solution: 130
  :view_secure_field: 131
  :edit_secure_field: 132
  :manage_scorecards: 133
  :manage_scores: 134
  :view_scores: 135
  :view_scorecards: 136
  :manage_teams: 137
  :view_omni_analytics: 138
  :manage_custom_objects: 139
  :manage_collaborators: 140
  :provide_access_via_mentions: 141
  :create_ticket: 142
  :update_ticket_with_send_and_set: 143
  :manage_chats: 144
  :create_public_note: 145
  :execute_scenario_automation: 146
  :manage_parent_child_tickets: 147
  :manage_linked_tickets: 148
  :create_service_tasks: 149
  :update_service_tasks: 150
  :delete_service_tasks: 151
  :service_task_assignee: 152
  :service_task_internal_assignee: 153
  :convert_to_topic: 154
  :ticket_assignee: 155
  :ticket_internal_assignee: 156
:max_value: 156
