/helpdesk/tickets: /a/tickets
/helpdesk/tickets/archived: /a/tickets/archived
/helpdesk/tickets/new: /a/tickets/new
/helpdesk: /a/
/: /a/
/helpdesk/dashboard: /a/
/helpdesk/dashboard/unresolved_tickets: /a/dashboard/unresolved_tickets
/admin/home: /a/admin/
/support/login: /a/
/solution/categories: /a/solutions/
/discussions: /a/forums/
/ticket_fields: /a/admin/
/admin/manage_languages: /a/admin/account/edit
/admin/email_configs: /a/admin/
/admin/portal: /a/admin/
/admin/chat_widgets: /a/admin/
/admin/widget_config: /a/admin/
/admin/contact_fields: /a/admin/
/admin/skills: /a/admin/
/admin/roles: /a/admin/
/admin/security: /a/admin/
/admin/business_calenders: /a/admin/
/admin/va_rules: /a/admin/va_rules
/admin/supervisor_rules: /a/admin/supervisor_rules
/admin/observer_rules: /a/admin/observer_rules
/admin/email_notifications: /a/admin/
/admin/custom_surveys: /a/admin/
/admin/email_command_settings: /a/admin/
/admin/zen_import: /a/admin/
/admin/phone: /a/admin/
/helpdesk/scenario_automations: /a/scenario_automations
/helpdesk/scenario_automations/new: /a/admin/
/admin/social/streams: /a/admin/
/social/facebook: /a/admin/
/account/edit: /a/admin/
/agents: /a/admin/
/agents/new: /a/admin/
/groups: /a/admin/groups
/groups/new: /a/admin/groups/new
/helpdesk/sla_policies: /a/admin/
/helpdesk/sla_policies/new: /a/admin/
/admin/products: /a/admin/
/helpdesk/tags: /a/admin/
/helpdesk/ticket_templates: /a/admin/
/helpdesk/ticket_templates/new: /a/admin/
/helpdesk/canned_responses/folders: /a/admin/
/admin/gamification: /a/admin/
/integrations/applications: /a/admin/integrations/applications
/account: /a/admin/
/account/cancel: /a/admin/account/cancel/
/subscription: /a/admin/
/subscription/billing: /a/admin/
/admin/day_passes: /a/admin/
/social/welcome: /a/social/
/helpdesk/tickets/compose_email: /a/tickets/compose-email
/search/all: /a/search/tickets
/helpdesk/dashboard/agent_status: /a/dashboard/agent_status/
/helpdesk/leaderboard/agents: /a/leaderboard/agents
/helpdesk/leaderboard/groups: /a/leaderboard/groups
