default: &default
  allowed_tasks:
    - "scheduler:sla"
    - "scheduler:sla_reminder"
    - "scheduler:supervisor"
    - "google_contacts:sync"
    - "facebook:realtime"
    - "facebook:push_likes"
    - "scheduler:facebook"
    - "facebook:realtime_fb_message"
    - "scheduler:premium_facebook"
    - "populate:spam_watcher_limits"
    - "spam_watcher:ticket_load"
    - "scheduler:twitter"
    - "scheduler:custom_stream_twitter"
    - "forum_moderation:scan"
    - "trial_subscriptions:rollback_trail_subscriptions_data"
    - "billing_info:enable_billing_info_update"

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
