common: &common
  access_key_id: dummy
  secret_access_key: dummy
  AWS_CALLING_FORMAT: SUBDOMAIN
  region: 'us-east-1'
  access_key_id_euc: access_key_id_euc
  secret_access_key_euc: secret_access_key_euc
  region_euc: 'eu-central-1'
  http_open_timeout: 10,
  http_read_timeout: 15,
  max_retries: 1

development:
  <<: *common
  bucket: cdn.freshpo.com
  reports_bucket: reports_archive_data_dev
  ticket_body: ticketbody-dev
  archive_ticket_body: archive-ticketbody-dev
  note_body: notebody-dev
  archive_note_body: archive-notebody-dev
  contact_note_body: contact-notebody-dev
  company_note_body: company-notebody-dev
  bi_reports_list_bucket: bi-reports-ticket-list-dev
  archive_email_storage_bucket: cdn.freshpo.com
  primary_email_storage_bucket: cdn.freshpo.com
  failed_email_storage_bucket: cdn.freshpo.com
  help_widget_bucket: help-widget-staging

staging:
  <<: *common
  bucket: cdn.freshpo.com
  reports_bucket: reports_archive_data_staging
  ticket_body: ticketbody-staging
  archive_ticket_body: archive-ticketbody-staging
  note_body: notebody-staging
  archive_note_body: archive-notebody-staging
  contact_note_body: contact-notebody-staging
  company_note_body: company-notebody-staging
  bi_reports_list_bucket: bi-reports-ticket-list-staging
  archive_email_storage_bucket: archive-email-data-staging
  primary_email_storage_bucket: primary-email-data-staging
  failed_email_storage_bucket: archive-email-data-staging
  help_widget_bucket: help-widget-staging

test:
  <<: *common
  bucket: fd-testbed
  reports_bucket: reports_archive_data_test
  ticket_body: ticketbody-test
  archive_ticket_body: archive-ticketbody-test
  note_body: notebody-test
  archive_note_body: archive-notebody-test
  contact_note_body: contact-notebody-test
  company_note_body: company-notebody-test
  bi_reports_list_bucket: bi-reports-ticket-list-test
  archive_email_storage_bucket: fd-testbed
  primary_email_storage_bucket: fd-testbed
  failed_email_storage_bucket: fd-testbed
  help_widget_bucket: help-widget-staging

production:
  access_key_id: dummy
  secret_access_key: dummy
  region: 'us-east-1'
  AWS_CALLING_FORMAT: SUBDOMAIN
  bucket: cdn.freshdesk.com
  reports_bucket: reports_archive_data_production
  ticket_body: ticketbody-production
  archive_ticket_body: archive-ticketbody-production
  note_body: notebody-production
  archive_note_body: archive-notebody-production
  contact_note_body: contact-notebody-production
  company_note_body: company-notebody-production
  bi_reports_list_bucket: bi-reports-ticket-list-production
  archive_email_storage_bucket: cdn.freshdesk.com
  primary_email_storage_bucket: cdn.freshdesk.com
  failed_email_storage_bucket: cdn.freshdesk.com
  help_widget_bucket: help-widget-production