defaults: &defaults
  repo_url: 'ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/fd-sandbox'
  public_key: '/Users/arvind/.ssh/aws_codecommit.pub'
  private_key: '/Users/arvind/.ssh/aws_codecommit'
  username: 'APKAJ3234SZUVVN5HTKQ'

development:
  <<: *defaults
slave:
  <<: *defaults
test:
  <<: *defaults
staging:
  <<: *defaults