:classification:
  :realtime:
    - premium_dispatcher
    - dispatcher
    - active_dispatcher
    - update_ticket_states
    - ticket_observer
    - rabbitmq_publish
    - esv2_count_index
    - account_creation_fixtures
    - detect_user_language
    - es_alias_queue
    - es_index_queue
    - new_es_index
    - account_info_to_dynamo
    - count_es_queue
    - round_robin_capping
    - assign_tickets_to_agents
    - send_and_set_observer
    - twitter_gnip_worker
    - sbrr_assignment
    - sbrr_user_toggle
    - sbrr_group_toggle
    - sbrr_config_user_skill
    - sbrr_config_agent_group
    - sbrr_config_skill
    - collaboration_publish
    - freshfone_notifications
    - freshfone_node
    - freshfone_trial_worker
    - livechat_worker
    - smart_filter_tweet_to_ticket
    - channel_framework_command
    - apigee_api
    - calculate_sla
    - add_agent_to_round_robin
    - toggle_agent_from_all_roundrobin_groups
    - default_data_population
    - twitter_reply
    - ocr_agent_sync
    - ocr_task_sync

  :central_realtime:
    - central_publish
    - active_ticket_central_publish
    - user_central_publish
    - ticket_field_central_publish
    - active_note_central_publish
    - company_central_publish
  :scheduled:
    - scheduled_reports
    - scheduled_reports_cleanup
    - chargebee_invoice
    - facebook
    - premium_facebook
    - twitter
    - premium_twitter
    - custom_twitter
    - send_activation_reminder_mail
    - block_account
  :occasional:
    - plan_change_workerv2
    - merge_contacts
    - plan_change
    - password_expiry
    - bulk_scenario
    - broadcast_note
    - notify_broadcast_message
    - update_user_language
    - solution_binarize_sync
    - bulk_ticket_actions
    - bulk_ticket_reply
    - merge_tickets
    - merge_tickets_attachments
    - pod_route_update
    - chargebee_add_subscription
    - partners_event_queue
    - reset_associations
    - link_tickets
    - dkim_verifier
    - dkim_general
    - bulk_child_tkt_creation
    - activation_worker
    - flush_portal_solution_cache
    - s3_retry_worker
    - reopen_tickets
    - skill_import
    - send_signup_activation_mail
    - upload_avatar_worker
    - solution_language_change
    - fb_split_tickets
    - facebook_delta
    - twitter_replay_worker
    - contact_export
    - company_export
    - product_feedback
    - freshcaller_migration_worker
    - ner_worker
    - smart_filter_initialise
    - smart_filter_feedback
    - launch_party_actions
    - ml_solutions_training
    - customer_note_body_queue
    - update_taggables_queue
    - suspended_ticket_central_publish
    - suspended_note_central_publish
    - send_domain_changed_mail
    - primary_language_change
    - freshops_service
  :maintainence:
    - select_all_tickets
    - select_all_batcher
    - update_tickets_company
    - update_all_callbacks
    - reset_group
    - reset_responder
    - reset_internal_group
    - reset_internal_agent
    - reset_gamification_score
    - export_agents
    - deactivate_monitorship
    - tag_uses_destroy
    - update_users_company_id
    - update_tickets_company_id
    - clear_tickets
    - agent_destroy_cleanup
    - delete_account
    - delete_spam_tickets
    - suspended_accounts_deletion
    - helpdesk_ticket_body_queue
    - helpdesk_note_body_queue
    - helpdesk_update_ticket_body_queue
    - helpdesk_update_note_body_queue
    - contact_import
    - company_import
    - data_export
    - parallel_report_exports
    - clear_moderation_records
    - empty_moderation_trash
    - generate_sitemap
    - clear_sitemap
    - sla_on_status_change
    - sandbox_sync
    - update_ticket_filter
    - modify_ticket_status
    - remove_secondary_companies
    - templates_cleanup
    - dev_notification_worker
    - natero_worker
    - reports_no_activity
    - bot_cleanup
    - update_time_zone
    - nullify_deleted_custom_field_data
    - restore_spam_tickets
    - contact_delete_forever
    - inline_image_shredder
    - deactivate_product_widgets
    - deactivate_filter_widgets
    - update_segment_filter
    - remove_encrypted_fields
  :external:
    - code_console_execution
    - integrations
    - api_webhook_rule
    - installed_app_business_rule
    - marketplace_apps
    - cti
    - contacts_sync_paid
    - contacts_sync
    - cloud_elements_delete
    - salesforce_integrated_resource_migrate
    - cloud_elements_logger_email
    - populate_account_setup
    - data_enrichment
    - email_service_provider
    - ebay_worker
    - ebay_message_worker
    - ebay_user_worker
    - webhook_v1_worker
    - update_sentiment
    - update_notes_sentiment
    - github
    - freshid_events
    - freshid_account_details_update
    - mixpanel_queue
    - freshid_agents_migration
    - run_rake_task
    - register_freshconnect
    - widget_upload_config
    - bot_email_reply
    - bot_email_ml_feedback
  :free:
    - free_sla
    - free_supervisor
    - free_sla_reminders
    - free_dispatcher
    - free_account_jobs
    - contacts_sync_free
    - free_ticket_central_publish
    - free_note_central_publish
  :mailbox_jobs:
    - mailbox_jobs
  :email:
    - active_account_jobs
    - premium_account_jobs
    - delayed_jobs
  :trial:
    - trial_sla
    - trial_supervisor
    - trial_sla_reminders
    - trial_dispatcher
    - trial_account_jobs
    - trial_facebook
    - trial_twitter
    - contacts_sync_trial
    - trial_ticket_central_publish
    - trial_note_central_publish
  :spam:
    - email_notification_spam_queue
    - spam_data_migration
    - kbase_content_spam_checker
    - forum_content_spam_checker
    - learn_spam_message
    - sendgrid_domain_updates
  :archive:
    - manual_publish
    - delayed_central_publish
    - archive_ticket_splitter
    - archive_build_create_ticket
    - archive_modify_ticket_association
    - archive_delete_ticket
    - archive_delete_ticket_dependencies
    - es_v2_queue
  :exports:
    - scheduled_ticket_export_config
    - scheduled_ticket_export
    - tickets_export_queue
    - long_running_ticket_export
    - premium_ticket_export
    - activity_export
    - report_export_queue
  :bulk_scheduled:
    - supervisor
    - sla
    - premium_sla
    - premium_supervisor
    - premium_sla_reminders
    - sla_reminders
  :gamification:
    - gamification_solution_quests
    - gamification_ticket_score
    - gamification_user_score
    - gamification_topic_quests
    - gamification_post_quests
    - gamification_ticket_quests
  :community:
    - spam_digest_mailer
    - merge_topics
    - forum_ban_user
    - forum_post_spam_marker
    - jira_acc_config_updates
    - report_post_worker
  :subscriptions:
    - subscription_events_queue
    - marketo_queue
    - track_customer_in_freshsales
