defaults: &defaults
  :verbose: true
  :require: ./config/environment.rb
  :concurrency: 5
  :redis_pool_size: 5
  :logfile: ./log/sidekiq.log
  :timeout: 30
  :queues:
    - [select_all_tickets]
    - [select_all_batcher]
    - [freshfone_notifications]
    - [freshfone_node]
    - [livechat_worker]
    - [freshfone_trial_worker]
    - [natero_worker]
    - [merge_contacts]
    - [sla]
    - [free_sla]
    - [trial_sla]
    - [premium_sla]
    - [premium_supervisor]
    - [supervisor]
    - [trial_supervisor]
    - [free_supervisor]
    - [facebook]
    - [premium_facebook]
    - [fb_split_tickets]
    - [facebook_comments]
    - [dev_notification_worker]
    - [upload_avatar_worker]
    - [twitter]
    - [premium_twitter]
    - [trial_facebook]
    - [facebook_delta]
    - [trial_twitter]
    - [custom_twitter]
    - [twitter_replay_worker]
    - [twitter_gnip_worker]
    - [rabbitmq_publish]
    - [plan_change]
    - [update_tickets_company]
    - [update_all_callbacks]
    - [reports_no_activity]
    - [es_alias_queue]
    - [es_index_queue]
    - [reset_group]
    - [reset_responder]
    - [reset_internal_group]
    - [reset_internal_agent]
    - [new_es_index]
    - [reset_gamification_score]
    - [solution_language_change]
    - [export_agents]
    - [ebay_worker]
    - [ebay_message_worker]
    - [ebay_user_worker]
    - [default]
    - [archive_ticket_splitter]
    - [archive_build_create_ticket]
    - [archive_modify_ticket_association]
    - [archive_delete_ticket]
    - [archive_delete_ticket_dependencies]
    - [chargebee_invoice]
    - [update_ticket_states]
    - [ticket_observer]
    - [password_expiry]
    - [sla_reminders]
    - [trial_sla_reminders]
    - [free_sla_reminders]
    - [premium_sla_reminders]
    - [deactivate_monitorship]
    - [es_v2_queue]
    - [tag_uses_destroy]
    - [bulk_scenario]
    - [github]
    - [webhook_v1_worker]
    - [report_export_queue]
    - [update_users_company_id]
    - [update_tickets_company_id]
    - [broadcast_note]
    - [notify_broadcast_message]
    - [solution_binarize_sync]
    - [clear_tickets]
    - [email_notification_spam_queue]
    - [update_user_language]
    - [integrations]
    - [bulk_ticket_actions]
    - [bulk_ticket_reply]
    - [api_webhook_rule]
    - [installed_app_business_rule]
    - [premium_dispatcher]
    - [dispatcher]
    - [trial_dispatcher]
    - [free_dispatcher]
    - [active_dispatcher]
    - [merge_tickets]
    - [merge_tickets_attachments]
    - [marketplace_apps]
    - [pod_route_update]
    - [agent_destroy_cleanup]
    - [delete_spam_tickets]
    - [suspended_accounts_deletion]
    - [helpdesk_ticket_body_queue]
    - [helpdesk_note_body_queue]
    - [helpdesk_update_ticket_body_queue]
    - [helpdesk_update_note_body_queue]
    - [contact_import]
    - [company_import]
    - [contact_export]
    - [data_export]
    - [delete_spam_tickets]
    - [suspended_accounts_deletion]
    - [tickets_export_queue]
    - [premium_ticket_export]
    - [long_running_ticket_export]
    - [chargebee_add_subscription]
    - [partners_event_queue]
    - [scheduled_reports]
    - [scheduled_reports_cleanup]
    - [account_info_to_dynamo]
    - [parallel_report_exports]
    - [count_es_queue]
    - [reset_associations]
    - [link_tickets]
    - [clear_moderation_records]
    - [empty_moderation_trash]
    - [sendgrid_domain_updates]
    - [generate_sitemap]
    - [clear_sitemap]
    - [cti]
    - [sla_on_status_change]
    - [sandbox_sync]
    - [update_sentiment]
    - [update_notes_sentiment]
    - [update_ticket_filter]
    - [esv2_count_index]
    - [round_robin_capping]
    - [assign_tickets_to_agents]
    - [modify_ticket_status]
    - [active_account_jobs]
    - [free_account_jobs]
    - [premium_account_jobs]
    - [trial_account_jobs]
    - [delayed_jobs]
    - [dkim_verifier]
    - [dkim_general]
    - [contacts_sync]
    - [contacts_sync_free]
    - [contacts_sync_paid]
    - [contacts_sync_trial]
    - [remove_secondary_companies]
    - [mailbox_jobs]
    - [sbrr_assignment]
    - [sbrr_user_toggle]
    - [sbrr_group_toggle]
    - [sbrr_config_user_skill]
    - [sbrr_config_agent_group]
    - [delete_account]
    - [templates_cleanup]
    - [bulk_child_tkt_creation]
    - [code_console_execution]
    - [flush_portal_solution_cache]
    - [plan_change_workerv2]
    - [learn_spam_message]
    - [s3_retry_worker]
    - [reopen_tickets]
    - [kbase_content_spam_checker]
    - [detect_user_language]
    - [cloud_elements_delete]
    - [salesforce_integrated_resource_migrate]
    - [cloud_elements_logger_email]
    - [populate_account_setup]
    - [manual_publish]

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults

slave:
  <<: *defaults

test:
  <<: *defaults
