development:
  twitter_realtime_queue: social_gnip_2_0_tweet_dev
  facebook_realtime_queue: social_fb_feed_dev
  search_etl_queue: search_etl_queue_dev
  spam_trash_delete_free_acc_queue: spam_trash_delete_free_acc_queue_dev
  spam_trash_delete_paid_acc_queue: spam_trash_delete_paid_acc_queue_dev
  count_etl_queue: count_etl_queue_dev
  analytics_etl_queue: analytics_etl_queue_dev
  sqs_es_index_queue: sqs_es_index_queue_dev
  custom_mailbox_realtime_queue: custom_mailbox_dev
  forums_moderation_queue: forum_moderation_dev
  helpdesk_reports_export_queue: helpdesk_reports_export_dev
  reports_etl_msg_queue: reports_etl_msgs_dev
  iris_etl_msg_queue: iris_etl_msgs_dev
  cti_call_queue: cti_call_dev
  activity_queue: fd_activities_dev
  activity_export_queue: fd_activities_export_dev
  reports_service_export_queue: reports_service_export_dev
  freshfone_call_tracker: freshfone_call_tracker_development
  cti_screen_pop: cti_screen_pop_dev
  fb_message_realtime_queue: social_fb_messenger_dev
  freshfone_call_notifier_queue: freshfone_call_notifier_development
  collab_agent_update_queue: collab_dev
  collab_ticket_update_queue: collab_dev
  auto_refresh_queue: auto_refresh_new_dev
  auto_refresh_alb_queue: auto_refresh_alb_dev
  agent_collision_queue: agent_collision_new_dev
  agent_collision_alb_queue: agent_collision_alb_dev
  marketplace_app_queue: marketplace_app_dev
  free_customer_email_queue: free_customer_email_queue_dev
  active_customer_email_queue: active_customer_email_queue_dev
  trial_customer_email_queue: trial_customer_email_queue_dev
  default_email_queue: default_email_queue_dev
  email_dead_letter_queue: failed_emails_queue_dev
  fd_email_failure_reference: fd_email_failure_reference_dev
  email_events_queue: fd_email_spam
  scheduled_ticket_export_config: scheduled_ticket_export_config_dev
  scheduled_ticket_export_complete: scheduled_ticket_export_complete_dev
  scheduled_export_payload_enricher_queue: scheduled_export_payload_enricher_queue_dev
  scheduled_ticket_export_queue: scheduled_ticket_export_queue_dev
  scheduled_user_export_queue: scheduled_user_export_queue_dev
  scheduled_company_export_queue: scheduled_company_export_queue_dev
  channel_framework_services: fd_cf_services_dev
  fd_scheduler_reminder_todo_queue: fd_scheduler_reminder_todo_queue_dev
  bot_feedback_queue: bot_feedback_staging
  custom_mailbox_status: custom_mailbox_status_dev
  fd_scheduler_export_cleanup_queue: fd_scheduler_export_cleanup_queue_dev
  fd_scheduler_downgrade_policy_reminder_queue: fd_scheduler_downgrade_policy_reminder_queue_dev
  search_etlqueue_maintenance: search_etl_queue_dev_maintenance
  count_etl_queue_maintenance: count_etl_queue_dev_maintenance
  analytics_etl_queue_maintenance: analytics_etl_queue_dev_maintenance
  suspended_account_cleanup_queue: suspended_account_cleanup_queue_dev
  email_rate_limiting_queue: email_rate_limiting_dev
  freddy_consumed_session_reminder_queue: freddy_consumed_session_reminder_queue
  switch_to_annual_notification_queue: switch_to_annual_notification_queue_dev
staging:
  twitter_realtime_queue: social_gnip_2_0_tweet_staging
  facebook_realtime_queue: social_fb_feed_staging
  search_etl_queue: search_etl_queue_staging
  spam_trash_delete_free_acc_queue: spam_trash_delete_free_acc_queue_staging
  spam_trash_delete_paid_acc_queue: spam_trash_delete_paid_acc_queue_staging
  count_etl_queue: count_etl_queue_staging
  analytics_etl_queue: analytics_etl_queue_staging
  custom_mailbox_realtime_queue: custom_mailbox_staging
  forums_moderation_queue: forum_moderation_staging_rails3
  helpdesk_reports_export_queue: helpdesk_reports_export_staging
  reports_etl_msg_queue: reports_etl_msgs_staging
  iris_etl_msg_queue: iris_etl_msgs_staging
  activity_queue: fd_activities_staging
  activity_export: fd_activities_export_staging
  reports_service_export_queue: reports_service_export_staging
  freshfone_call_tracker: freshfone_call_tracker_staging
  cti_screen_pop: cti_screen_pop_staging
  cti_call_queue: cti_call_staging
  fb_message_realtime_queue: social_fb_messenger_staging
  freshfone_call_notifier_queue: freshfone_call_notifier_staging
  collab_agent_update_queue: collab_agent_update_staging
  collab_ticket_update_queue: collab_ticket_update_staging
  auto_refresh_queue: auto_refresh_new_staging
  auto_refresh_alb_queue: auto_refresh_alb_staging
  agent_collision_queue: agent_collision_new_staging
  agent_collision_alb_queue: agent_collision_alb_staging
  marketplace_app_queue: marketplace_app_staging
  free_customer_email_queue: free_customer_email_queue_staging
  active_customer_email_queue: active_customer_email_queue_staging
  trial_customer_email_queue: trial_customer_email_queue_staging
  default_email_queue: default_email_queue_staging
  email_dead_letter_queue: failed_emails_queue_staging
  fd_email_failure_reference: fd_email_failure_reference_staging
  scheduled_ticket_export_config: scheduled_ticket_export_config_staging
  scheduled_ticket_export_complete: scheduled_ticket_export_complete_staging
  scheduled_export_payload_enricher_queue: scheduled_export_payload_enricher_queue_staging
  scheduled_ticket_export_queue: scheduled_ticket_export_queue_staging
  scheduled_user_export_queue: scheduled_user_export_queue_staging
  scheduled_company_export_queue: scheduled_company_export_queue_staging
  bot_feedback_queue: bot_feedback_staging
  search_etlqueue_maintenance: search_etl_queue_staging_maintenance
  count_etl_queue_maintenance: count_etl_queue_staging_maintenance
  analytics_etl_queue_maintenance: analytics_etl_queue_staging_maintenance
  email_rate_limiting_queue: email_rate_limiting_staging
  freddy_consumed_session_reminder_queue: freddy_consumed_session_reminder_queue

production:
  twitter_realtime_queue: social_gnip_tweet_production
  facebook_realtime_queue: social_fb_feed_production
  search_etl_queue: search_etl_queue_production
  spam_trash_delete_free_acc_queue: spam_trash_delete_free_acc_queue_production
  spam_trash_delete_paid_acc_queue: spam_trash_delete_paid_acc_queue_production
  count_etl_queue: count_etl_queue_procution
  analytics_etl_queue: analytics_etl_queue_procution
  custom_mailbox_realtime_queue: custom_mailbox_production
  forums_moderation_queue: forum_moderation_production
  helpdesk_reports_export_queue: helpdesk_reports_export_production
  reports_etl_msg_queue: reports_etl_msgs_production
  iris_etl_msg_queue: iris_etl_msgs_production
  activity_queue: fd_activities_production
  reports_service_export_queue: reports_service_export_production
  freshfone_call_tracker: freshfone_call_tracker_production
  cti_screen_pop: cti_screen_pop_production
  cti_call_queue: cti_call_production
  fb_message_realtime_queue: social_fb_messenger_prod
  freshfone_call_notifier_queue: freshfone_call_notifier_production
  collab_agent_update_queue: collab_agent_update_production
  collab_ticket_update_queue: collab_ticket_update_production
  auto_refresh_queue: auto_refresh_new_production
  auto_refresh_alb_queue: auto_refresh_alb_production
  agent_collision_queue: agent_collision_new_production
  agent_collision_alb_queue: agent_collision_alb_production
  marketplace_app_queue: marketplace_app_production
  free_customer_email_queue: free_customer_email_queue_production
  active_customer_email_queue: active_customer_email_queue_production
  trial_customer_email_queue: trial_customer_email_queue_production
  default_email_queue: default_email_queue_production
  email_dead_letter_queue: failed_emails_queue_production
  fd_email_failure_reference: fd_email_failure_reference_production
  scheduled_ticket_export_config: scheduled_ticket_export_config_production
  scheduled_ticket_export_complete: scheduled_ticket_export_complete_prod
  scheduled_export_payload_enricher_queue: scheduled_export_payload_enricher_queue_production
  scheduled_ticket_export_queue: scheduled_ticket_export_queue_production
  scheduled_user_export_queue: scheduled_user_export_queue_production
  scheduled_company_export_queue: scheduled_company_export_queue_production
  bot_feedback_queue: bot_feedback_production
  search_etlqueue_maintenance: search_etl_queue_production_maintenance
  count_etl_queue_maintenance: count_etl_queue_production_maintenance
  analytics_etl_queue_maintenance: analytics_etl_queue_production_maintenance
  email_rate_limiting_queue: email_rate_limiting_production
  freddy_consumed_session_reminder_queue: freddy_consumed_session_reminder_production

test:
  twitter_realtime_queue: social_gnip_2_0_tweet_test
  facebook_realtime_queue: social_fb_feed_test
  search_etl_queue: search_etl_queue_test
  spam_trash_delete_free_acc_queue: spam_trash_delete_free_acc_queue_test
  spam_trash_delete_paid_acc_queue: spam_trash_delete_paid_acc_queue_test
  count_etl_queue: count_etl_queue_test
  analytics_etl_queue: analytics_etl_queue_test
  custom_mailbox_realtime_queue: custom_mailbox_test
  forums_moderation_queue: forum_moderation_test
  helpdesk_reports_export_queue: helpdesk_reports_export_test
  reports_etl_msg_queue: reports_etl_msgs_test
  iris_etl_msg_queue: iris_etl_msgs_test
  activity_queue: fd_activities_test
  reports_service_export_queue: reports_service_export_test
  freshfone_call_tracker: freshfone_call_tracker_test
  cti_screen_pop: cti_screen_pop_test
  cti_call_queue: cti_call_test
  fb_message_realtime_queue: social_fb_messenger_dev
  freshfone_call_notifier_queue: freshfone_call_notifier_test
  collab_agent_update_queue: collab_agent_update_test
  collab_ticket_update_queue: collab_ticket_update_test
  auto_refresh_queue: auto_refresh_new_test
  agent_collision_queue: agent_collision_new_test
  marketplace_app_queue: marketplace_app_test
  free_customer_email_queue: free_customer_email_queue_test
  active_customer_email_queue: active_customer_email_queue_test
  trial_customer_email_queue: trial_customer_email_queue_test
  default_email_queue: default_email_queue_test
  email_dead_letter_queue: failed_emails_queue_test
  fd_email_failure_reference: fd_email_failure_reference_test
  scheduled_ticket_export_config: scheduled_ticket_export_config_test
  scheduled_ticket_export_complete: scheduled_ticket_export_complete_test
  scheduled_export_payload_enricher_queue: scheduled_export_payload_enricher_queue_test
  scheduled_ticket_export_queue: scheduled_ticket_export_queue_test
  scheduled_user_export_queue: scheduled_user_export_queue_test
  scheduled_company_export_queue: scheduled_company_export_queue_test
  fd_scheduler_reminder_todo_queue: fd_scheduler_reminder_todo_queue_test
  bot_feedback_queue: bot_feedback_test
  fd_scheduler_export_cleanup_queue: fd_scheduler_export_cleanup_queue_test
  fd_scheduler_downgrade_policy_reminder_queue: fd_scheduler_downgrade_policy_reminder_queue_test
  search_etlqueue_maintenance: search_etl_queue_test_maintenance
  count_etl_queue_maintenance: count_etl_queue_test_maintenance
  analytics_etl_queue_maintenance: analytics_etl_queue_test_maintenance
  suspended_account_cleanup_queue: suspended_account_cleanup_queue_test
  email_rate_limiting_queue: email_rate_limiting_test
  freddy_consumed_session_reminder_queue: freddy_consumed_session_reminder_queue_test
  switch_to_annual_notification_queue: switch_to_annual_notification_queue_test
