consumer_token: 
    production: dJ8tRu32g8UfWpPgs3bg
    staging: dr1GMNCkYqUqjPTvWoY4nQ
    development: dr1GMNCkYqUqjPTvWoY4nQ
consumer_secret: 
    production: Brp3pT6z9JTGvCB1dWLEIHLBEre8Yy9lEFGZXwfUo
    staging: QUbXWcl5dOAdylf3eSCjD0XnFRpUOErUVId3RKMc
    development: QUbXWcl5dOAdylf3eSCjD0XnFRpUOErUVId3RKMc
callback_url:
  production: http://twitterintegration.heroku.com/twitter/auth
  development: http://localhost:3000/twitter/authdone