
default_fields:
    date_time: &date_time
        handler: date_time
    
    from_email:
        handler: text
        
    to_email:
        handler: text

    subject:
        handler: text

    description:
        handler: text
        
    subject_or_description:
        handler: text_array

    priority:
        handler: numeric
      
    tag_names:
        handler: text_array
        
    ticket_type:
        handler: numeric
    
    status:
        handler: numeric

    source:
        handler: numeric

    contact:
        handler: text

    company:
        handler: text
        
    created_at:
        <<: *date_time
    opened_at:
        <<: *date_time
    pending_since:
        <<: *date_time
    resolved_at:
        <<: *date_time
    closed_at:
        <<: *date_time
    first_assigned_at:
        <<: *date_time
    assigned_at:
        <<: *date_time
    requester_responded_at:
        <<: *date_time
    agent_responded_at:
        <<: *date_time
    first_response_due:
        <<: *date_time
    due_by:
        <<: *date_time

handlers:
    text: Va::Handlers::Text
    text_array: Va::Handlers::TextArray
    numeric: Va::Handlers::Numeric
    date_time: Va::Handlers::DateTime
    dropdown:  Va::Handlers::Text
    checkbox: Va::Handlers::Boolean
