:plan_groups:
  sprout:
    - Sprout
    - Sprout Classic
    - Sprout Jan 17
  blossom:
    - Blossom
    - Blossom Classic
    - Blossom Jan 17
  garden:
    - Garden
    - Garden Classic
    - Garden Jan 17
  estate:
    - Estate
    - Estate Classic
    - Estate Jan 17
  forest:
    - Forest
    - Forest Jan 17

:max_limits:
  :save_report:
    :user:
      estate: 50
      forest: 50
      :default: 25
  :scheduled_report:
    :user:
      garden: 10
      estate: 20
      forest: 20
      :default: 10
    :account:
      garden: 70
      estate: 100
      forest: 100
      :default: 70

:data_refresh_frequency:
  default: 1440
  sprout: 1440
  blossom: 1440
  garden: 60
  estate: 60
  forest: 30
  enterprise_reporting: 240

:plan_constraints:
  enable_ticket_list:
    - garden
    - estate
    - forest
  disable_date_lag:
    - garden
    - estate
    - forest
  enable_save_report:
    - blossom
    - garden
    - estate
    - forest
  enable_schedule_report:
    - garden
    - estate
    - forest
  enable_qna_insights:
    - estate
    - forest

:plan_exclude_filters:
  :glance: 
    blossom:
      - :agent_id
      - :group_id
    garden:
      - :agent_id
      - :group_id

:global_exclude_filters:
  :customer_report:
    - :company_id
